// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Netscape cookie format support for CLI session storage.
//!
//! This module provides functions to read and write cookies in the Netscape cookie
//! format, which is used by many tools including curl and wget.
//!
//! The cookie file is stored at `$XDG_STATE_HOME/vouch/cookie.txt`
//! (`~/.local/state/vouch/cookie.txt` by default) with 0600 permissions on Unix.

use anyhow::{Context, Result};
use std::fs;
use std::path::PathBuf;

/// A session cookie in Netscape format.
#[derive(Clone)]
pub struct SessionCookie {
    /// Domain for the cookie (e.g., "vouch.example.com").
    pub domain: String,
    /// Whether the cookie is available to subdomains.
    pub include_subdomains: bool,
    /// Path for the cookie (usually "/").
    pub path: String,
    /// Whether the cookie requires HTTPS.
    pub secure: bool,
    /// Expiration time as Unix timestamp.
    pub expires: i64,
    /// Cookie name.
    pub name: String,
    /// Cookie value (the session token).
    pub value: String,
}

// Custom Debug that redacts value to prevent accidental log exposure.
impl std::fmt::Debug for SessionCookie {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SessionCookie")
            .field("domain", &self.domain)
            .field("include_subdomains", &self.include_subdomains)
            .field("path", &self.path)
            .field("secure", &self.secure)
            .field("expires", &self.expires)
            .field("name", &self.name)
            .field("value", &"[REDACTED]")
            .finish()
    }
}

impl SessionCookie {
    /// Create a new session cookie.
    pub fn new(domain: &str, value: &str, expires: i64) -> Self {
        Self {
            domain: domain.to_string(),
            include_subdomains: false,
            path: "/".to_string(),
            secure: true,
            expires,
            name: crate::SESSION_COOKIE_NAME.to_string(),
            value: value.to_string(),
        }
    }

    /// Format as a Netscape cookie line.
    fn to_netscape_line(&self) -> String {
        format!(
            "{}\t{}\t{}\t{}\t{}\t{}\t{}",
            self.domain,
            if self.include_subdomains {
                "TRUE"
            } else {
                "FALSE"
            },
            self.path,
            if self.secure { "TRUE" } else { "FALSE" },
            self.expires,
            self.name,
            self.value
        )
    }
}

/// Get the path to the cookie file.
///
/// Returns `$XDG_STATE_HOME/vouch/cookie.txt` (`~/.local/state/vouch/cookie.txt`
/// by default).
pub fn cookie_path() -> Result<PathBuf> {
    crate::paths::cookie_file().context("could not determine home directory")
}

/// Write a session cookie to the cookie file.
///
/// Creates the cookie file with restrictive permissions (0600 on Unix).
/// Overwrites any existing cookie.
pub fn write_cookie(cookie: &SessionCookie) -> Result<()> {
    let path = cookie_path()?;

    // Ensure parent directory exists with owner-only (0700) permissions, matching
    // the rest of vouch's state directory (audit log, migrated layout).
    if let Some(parent) = path.parent() {
        crate::paths::prepare_private_dir(parent)
            .with_context(|| format!("failed to create directory {}", parent.display()))?;
    }

    let content = format!(
        "# Netscape HTTP Cookie File\n\
         # https://curl.se/docs/http-cookies.html\n\
         # This file was generated by vouch. Do not edit.\n\
         \n\
         {}\n",
        cookie.to_netscape_line()
    );

    // Write with restrictive permissions (0600)
    #[cfg(unix)]
    {
        use std::io::Write;
        use std::os::unix::fs::OpenOptionsExt;
        let mut options = fs::OpenOptions::new();
        options.write(true).create(true).truncate(true).mode(0o600);
        let mut file = options
            .open(&path)
            .with_context(|| format!("failed to create cookie file {}", path.display()))?;
        file.write_all(content.as_bytes())
            .with_context(|| format!("failed to write cookie to {}", path.display()))?;
    }

    #[cfg(not(unix))]
    {
        fs::write(&path, &content)
            .with_context(|| format!("failed to write cookie to {}", path.display()))?;
    }

    Ok(())
}

/// Clear the cookie file (logout).
///
/// Removes the cookie file if it exists.
pub fn clear_cookie() -> Result<()> {
    let path = cookie_path()?;

    if path.exists() {
        fs::remove_file(&path)
            .with_context(|| format!("failed to remove cookie file {}", path.display()))?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_netscape_format() {
        let cookie = SessionCookie::new("vouch.example.com", "token123", 1_737_849_600);
        let line = cookie.to_netscape_line();
        assert_eq!(
            line,
            "vouch.example.com\tFALSE\t/\tTRUE\t1737849600\t__Host-vouch_session\ttoken123"
        );
    }
}
