//! Semantic type markers for FIDO2 data.
//!
//! This module provides type aliases that give semantic meaning to binary data.
//! Using these types instead of raw `Vec<u8>` provides:
//!
//! 1. **Compile-time safety**: Can't accidentally pass a credential_id where a challenge is expected
//! 2. **Documentation**: The type name documents what the data represents
//! 3. **Encoding tracking**: `Challenge<Raw>` vs `Challenge<Base64Url>`
//!
//! # Type Structure
//!
//! ```text
//! Encoded<ChallengeData, Raw>
//!         ↑               ↑
//!         │               └── Encoding (Raw bytes vs Base64Url string)
//!         └── Semantic marker (what the data represents)
//! ```
//!
//! # Example
//!
//! ```rust
//! use vouch_common::fido2_types::{Challenge, CredentialId};
//! use vouch_common::encoding::{Raw, Base64Url, ConvertEncoding};
//!
//! // Create a challenge
//! let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
//!
//! // This won't compile - different semantic types!
//! // let cred_id: CredentialId<Raw> = challenge; // ERROR!
//!
//! // Convert encoding for browser API
//! let challenge_b64: Challenge<Base64Url> = challenge.to_base64url();
//! ```

use crate::encoding::{Base64Url, Encoded, Raw};

// ============================================================================
// Semantic Markers (Zero-sized types)
// ============================================================================

/// Marker for WebAuthn challenge data.
///
/// A challenge is a random value generated by the server to prevent replay attacks.
/// Typically 32 bytes.
#[derive(Debug, Clone, Copy)]
pub struct ChallengeData;

/// Marker for credential ID data.
///
/// The credential ID uniquely identifies a WebAuthn credential.
/// Generated by the authenticator during registration.
#[derive(Debug, Clone, Copy)]
pub struct CredentialIdData;

/// Marker for COSE public key data.
///
/// The public key in COSE (CBOR Object Signing and Encryption) format.
/// Used to verify authenticator signatures.
#[derive(Debug, Clone, Copy)]
pub struct CoseKeyData;

/// Marker for authenticator data.
///
/// Contains the RP ID hash, flags, counter, and optional extensions.
/// Part of both registration and authentication responses.
#[derive(Debug, Clone, Copy)]
pub struct AuthenticatorDataMarker;

/// Marker for client data JSON.
///
/// JSON object containing type, challenge, origin, and cross-origin info.
/// Hashed as part of signature verification.
#[derive(Debug, Clone, Copy)]
pub struct ClientDataJsonData;

/// Marker for signature data.
///
/// The cryptographic signature from the authenticator.
/// Format depends on the algorithm (DER for ECDSA, raw for Ed25519).
#[derive(Debug, Clone, Copy)]
pub struct SignatureData;

/// Marker for user handle data.
///
/// Server-provided user identifier stored on the authenticator.
/// Used with discoverable credentials to identify the user.
#[derive(Debug, Clone, Copy)]
pub struct UserHandleData;

/// Marker for attestation object data.
///
/// Contains the authenticator data and attestation statement.
/// Only present during registration (not authentication).
#[derive(Debug, Clone, Copy)]
pub struct AttestationObjectData;

// ============================================================================
// Type Aliases
// ============================================================================

/// A WebAuthn challenge with tracked encoding.
pub type Challenge<E> = Encoded<ChallengeData, E>;

/// A credential ID with tracked encoding.
pub type CredentialId<E> = Encoded<CredentialIdData, E>;

/// A COSE public key with tracked encoding.
pub type CoseKey<E> = Encoded<CoseKeyData, E>;

/// Authenticator data with tracked encoding.
pub type AuthData<E> = Encoded<AuthenticatorDataMarker, E>;

/// Client data JSON with tracked encoding.
pub type ClientDataJson<E> = Encoded<ClientDataJsonData, E>;

/// A signature with tracked encoding.
pub type Signature<E> = Encoded<SignatureData, E>;

/// A user handle with tracked encoding.
pub type UserHandle<E> = Encoded<UserHandleData, E>;

/// An attestation object with tracked encoding.
pub type AttestationObject<E> = Encoded<AttestationObjectData, E>;

// ============================================================================
// Convenience Type Aliases for Common Cases
// ============================================================================

/// Raw challenge bytes.
pub type RawChallenge = Challenge<Raw>;

/// Raw credential ID bytes.
pub type RawCredentialId = CredentialId<Raw>;

/// Raw COSE key bytes.
pub type RawCoseKey = CoseKey<Raw>;

/// Raw authenticator data bytes.
pub type RawAuthData = AuthData<Raw>;

/// Raw client data JSON bytes.
pub type RawClientDataJson = ClientDataJson<Raw>;

/// Raw signature bytes.
pub type RawSignature = Signature<Raw>;

/// Raw user handle bytes.
pub type RawUserHandle = UserHandle<Raw>;

/// Raw attestation object bytes.
pub type RawAttestationObject = AttestationObject<Raw>;

/// Base64url-encoded challenge (for browser APIs).
pub type Base64UrlChallenge = Challenge<Base64Url>;

/// Base64url-encoded credential ID (for browser APIs).
pub type Base64UrlCredentialId = CredentialId<Base64Url>;

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::encoding::ConvertEncoding;

    #[test]
    fn test_challenge_creation() {
        let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
        assert_eq!(challenge.as_bytes(), &[1, 2, 3]);
    }

    #[test]
    fn test_credential_id_creation() {
        let cred_id: CredentialId<Raw> = CredentialId::from_raw(vec![4, 5, 6]);
        assert_eq!(cred_id.as_bytes(), &[4, 5, 6]);
    }

    #[test]
    fn test_encoding_conversion() {
        let raw: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
        let b64: Challenge<Base64Url> = raw.to_base64url();
        assert_eq!(b64.as_base64url(), "AQID");
    }

    #[test]
    fn test_type_aliases() {
        // Verify type aliases work as expected
        let _: RawChallenge = RawChallenge::from_raw(vec![1, 2, 3]);
        let _: RawCredentialId = RawCredentialId::from_raw(vec![4, 5, 6]);
        let _: RawCoseKey = RawCoseKey::from_raw(vec![7, 8, 9]);
    }

    #[test]
    fn test_serde_round_trip() {
        let original: RawChallenge = RawChallenge::from_raw(vec![1, 2, 3]);
        let json = serde_json::to_string(&original).unwrap();
        let decoded: RawChallenge = serde_json::from_str(&json).unwrap();
        assert_eq!(original.as_bytes(), decoded.as_bytes());
    }

    #[test]
    fn test_from_vec() {
        let data = vec![1u8, 2, 3];
        let challenge: RawChallenge = data.into();
        assert_eq!(challenge.as_bytes(), &[1, 2, 3]);
    }

    #[test]
    fn test_into_vec() {
        let challenge: RawChallenge = RawChallenge::from_raw(vec![1, 2, 3]);
        let data: Vec<u8> = challenge.into();
        assert_eq!(data, vec![1, 2, 3]);
    }

    // Note: This test verifies compile-time type safety.
    // The following would NOT compile if uncommented:
    //
    // fn compile_error_test() {
    //     let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
    //     let _cred_id: CredentialId<Raw> = challenge; // ERROR: mismatched types
    // }
}
