// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Semantic type markers for FIDO2 data.
//!
//! This module provides type aliases that give semantic meaning to binary data.
//! Using these types instead of raw `Vec<u8>` provides:
//!
//! 1. **Compile-time safety**: Can't accidentally pass a credential_id where a challenge is expected
//! 2. **Documentation**: The type name documents what the data represents
//! 3. **Encoding tracking**: `Challenge<Raw>` vs `Challenge<Base64Url>`
//!
//! # Type Structure
//!
//! ```text
//! Encoded<ChallengeData, Raw>
//!         ↑               ↑
//!         │               └── Encoding (Raw bytes vs Base64Url string)
//!         └── Semantic marker (what the data represents)
//! ```
//!
//! # Example
//!
//! ```rust
//! use vouch_common::fido2_types::{Challenge, CredentialId};
//! use vouch_common::encoding::{Raw, Base64Url, ConvertEncoding};
//!
//! // Create a challenge
//! let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
//!
//! // This won't compile - different semantic types!
//! // let cred_id: CredentialId<Raw> = challenge; // ERROR!
//!
//! // Convert encoding for browser API
//! let challenge_b64: Challenge<Base64Url> = challenge.to_base64url();
//! ```

use crate::encoding::{Bounds, Encoded};
use serde::{Deserialize, Deserializer, Serialize};

// ============================================================================
// Semantic Markers (Zero-sized types)
// ============================================================================

/// Marker for WebAuthn challenge data.
///
/// A challenge is a random value generated by the server to prevent replay attacks.
/// Typically 32 bytes.
#[derive(Debug, Clone, Copy)]
pub struct ChallengeData;

/// Marker for credential ID data.
///
/// The credential ID uniquely identifies a WebAuthn credential.
/// Generated by the authenticator during registration.
#[derive(Debug, Clone, Copy)]
pub struct CredentialIdData;

/// Marker for COSE public key data.
///
/// The public key in COSE (CBOR Object Signing and Encryption) format.
/// Used to verify authenticator signatures.
#[derive(Debug, Clone, Copy)]
pub struct CoseKeyData;

/// Marker for authenticator data.
///
/// Contains the RP ID hash, flags, counter, and optional extensions.
/// Part of both registration and authentication responses.
#[derive(Debug, Clone, Copy)]
pub struct AuthenticatorDataMarker;

/// Marker for client data JSON.
///
/// JSON object containing type, challenge, origin, and cross-origin info.
/// Hashed as part of signature verification.
#[derive(Debug, Clone, Copy)]
pub struct ClientDataJsonData;

/// Marker for signature data.
///
/// The cryptographic signature from the authenticator.
/// Format depends on the algorithm (DER for ECDSA, raw for Ed25519).
#[derive(Debug, Clone, Copy)]
pub struct SignatureData;

/// Marker for user handle data.
///
/// Server-provided user identifier stored on the authenticator.
/// Used with discoverable credentials to identify the user.
#[derive(Debug, Clone, Copy)]
pub struct UserHandleData;

/// Marker for attestation object data.
///
/// Contains the authenticator data and attestation statement.
/// Only present during registration (not authentication).
#[derive(Debug, Clone, Copy)]
pub struct AttestationObjectData;

// ============================================================================
// Length Bounds
// ============================================================================
//
// Each marker's accepted decoded byte range. `Encoded<T, E>` applies these
// during deserialization, so an out-of-range value never reaches a handler,
// a verifier, or the document store — and no handler carries a length check
// that could be dropped or reordered.

impl Bounds for ChallengeData {
    /// WebAuthn Level 2 §13.4.3 (Cryptographic Challenges):
    ///
    /// > In order to prevent replay attacks, the challenges MUST contain
    /// > enough entropy to make guessing them infeasible. Challenges SHOULD
    /// > therefore be at least 16 bytes long.
    ///
    /// <https://www.w3.org/TR/webauthn-2/#sctn-cryptographic-challenges>
    ///
    /// Vouch issues 32-byte challenges. The ceiling is a Vouch limit; the
    /// specification sets none.
    const MIN_BYTES: usize = 16;
    const MAX_BYTES: usize = 1024;
}

impl Bounds for CredentialIdData {
    /// WebAuthn Level 2 §4 (Terminology), defining "Credential ID":
    ///
    /// > Credential IDs are generated by authenticators in two forms:
    /// >
    /// > 1. At least 16 bytes that include at least 100 bits of entropy, or
    /// > 2. The public key credential source, without its Credential ID or
    /// >    mutable items, encrypted so only its managing authenticator can
    /// >    decrypt it.
    ///
    /// <https://www.w3.org/TR/webauthn-2/#credential-id>
    ///
    /// The second form is at least as long as the first, so 16 is the floor
    /// for both. The ceiling is a Vouch limit matching what CTAP2
    /// authenticators report as `maxCredentialIdLength` in practice; the
    /// specification sets none.
    const MIN_BYTES: usize = 16;
    const MAX_BYTES: usize = 1023;
}

impl Bounds for CoseKeyData {
    /// A P-256 COSE key is around 77 bytes; the ceiling leaves room for
    /// larger curves and RSA without admitting an arbitrary blob.
    const MIN_BYTES: usize = 1;
    const MAX_BYTES: usize = 8 * 1024;
}

impl Bounds for AuthenticatorDataMarker {
    /// Authenticator data is 37 bytes plus attested credential data and
    /// extensions. The floor stays at 1 rather than 37 so a truncated value
    /// is reported by the parser, which names the missing field.
    const MIN_BYTES: usize = 1;
    const MAX_BYTES: usize = 3 * 1024;
}

impl Bounds for ClientDataJsonData {
    /// Client data JSON is a small object: type, challenge, origin, and
    /// optional cross-origin flag.
    const MIN_BYTES: usize = 1;
    const MAX_BYTES: usize = 3 * 1024;
}

impl Bounds for SignatureData {
    /// ECDSA and EdDSA signatures are under 100 bytes; the ceiling leaves
    /// room for larger algorithms.
    const MIN_BYTES: usize = 1;
    const MAX_BYTES: usize = 768;
}

impl Bounds for UserHandleData {
    /// WebAuthn Level 2 §4 (Terminology), defining "User Handle":
    ///
    /// > A user handle is an opaque byte sequence with a maximum size of 64
    /// > bytes, and is not meant to be displayed to the user.
    ///
    /// <https://www.w3.org/TR/webauthn-2/#user-handle>
    ///
    /// Vouch user handles are 16-byte UUIDs. The ceiling here is looser than
    /// the specification's 64 so an oversized handle is reported by the UUID
    /// parse, which says what the value should have been.
    const MIN_BYTES: usize = 1;
    const MAX_BYTES: usize = 192;
}

impl Bounds for AttestationObjectData {
    /// Hardware attestations carrying a certificate chain are typically
    /// under 4 KB.
    const MIN_BYTES: usize = 1;
    const MAX_BYTES: usize = 12 * 1024;
}

// ============================================================================
// State Token
// ============================================================================

/// The signed state token a `.../complete` request carries back.
///
/// Deserialization enforces the ceiling, so an oversized token is rejected at
/// the request boundary and no handler carries a length check of its own.
/// Responses hand out a plain `String` — the bound guards untrusted input,
/// and a token this server just minted is not that.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct StateToken(String);

impl StateToken {
    /// Largest accepted token, in bytes. A Vouch limit; a JWT has no
    /// standard maximum length.
    pub const MAX_BYTES: usize = 8 * 1024;

    /// The token as a string slice.
    #[inline]
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl From<String> for StateToken {
    #[inline]
    fn from(token: String) -> Self {
        Self(token)
    }
}

impl<'de> Deserialize<'de> for StateToken {
    fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error> {
        let token = String::deserialize(deserializer)?;
        if token.len() > Self::MAX_BYTES {
            return Err(serde::de::Error::custom(format!(
                "state token exceeds {} bytes",
                Self::MAX_BYTES
            )));
        }
        Ok(Self(token))
    }
}

// ============================================================================
// Type Aliases
// ============================================================================

/// A WebAuthn challenge with tracked encoding.
pub type Challenge<E> = Encoded<ChallengeData, E>;

/// A credential ID with tracked encoding.
pub type CredentialId<E> = Encoded<CredentialIdData, E>;

/// A COSE public key with tracked encoding.
pub type CoseKey<E> = Encoded<CoseKeyData, E>;

/// Authenticator data with tracked encoding.
pub type AuthData<E> = Encoded<AuthenticatorDataMarker, E>;

/// Client data JSON with tracked encoding.
pub type ClientDataJson<E> = Encoded<ClientDataJsonData, E>;

/// A signature with tracked encoding.
pub type Signature<E> = Encoded<SignatureData, E>;

/// A user handle with tracked encoding.
pub type UserHandle<E> = Encoded<UserHandleData, E>;

/// An attestation object with tracked encoding.
pub type AttestationObject<E> = Encoded<AttestationObjectData, E>;

// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    reason = "test code: panic on assertion failure is acceptable"
)]
mod tests {
    use super::*;
    use crate::encoding::{Base64Url, ConvertEncoding, Raw};

    #[test]
    fn test_challenge_creation() {
        let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
        assert_eq!(challenge.as_bytes(), &[1, 2, 3]);
    }

    #[test]
    fn test_credential_id_creation() {
        let cred_id: CredentialId<Raw> = CredentialId::from_raw(vec![4, 5, 6]);
        assert_eq!(cred_id.as_bytes(), &[4, 5, 6]);
    }

    #[test]
    fn test_encoding_conversion() {
        let raw: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
        let b64: Challenge<Base64Url> = raw.to_base64url();
        assert_eq!(b64.as_base64url(), "AQID");
    }

    #[test]
    fn test_serde_round_trip() {
        // 32 bytes: `ChallengeData`'s floor is the 16 bytes WebAuthn Level 2
        // §13.4.3 asks for, so a 3-byte challenge no longer deserializes.
        let original: Challenge<Raw> = Challenge::from_raw(vec![1; 32]);
        let json = serde_json::to_string(&original).unwrap();
        let decoded: Challenge<Raw> = serde_json::from_str(&json).unwrap();
        assert_eq!(original.as_bytes(), decoded.as_bytes());
    }

    #[test]
    fn test_from_vec() {
        let data = vec![1u8, 2, 3];
        let challenge: Challenge<Raw> = data.into();
        assert_eq!(challenge.as_bytes(), &[1, 2, 3]);
    }

    #[test]
    fn test_into_vec() {
        let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
        let data: Vec<u8> = challenge.into();
        assert_eq!(data, vec![1, 2, 3]);
    }

    // Note: This test verifies compile-time type safety.
    // The following would NOT compile if uncommented:
    //
    // fn compile_error_test() {
    //     let challenge: Challenge<Raw> = Challenge::from_raw(vec![1, 2, 3]);
    //     let _cred_id: CredentialId<Raw> = challenge; // ERROR: mismatched types
    // }
}
