[package]
name = "vouch-common"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Shared types for vouch CLI and server"

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["std"] }
base64 = { workspace = true, features = ["std"] }
ciborium = { workspace = true }
dirs = { workspace = true }
gethostname = { workspace = true }
hex = { workspace = true, features = ["std"] }
hickory-resolver = { workspace = true }
jiff = { workspace = true, features = ["std", "serde", "tz-system"] }
reqwest = { workspace = true, features = ["json", "rustls", "form"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
uuid = { workspace = true, features = ["v7", "serde", "std"] }
