// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Per-organization OIDC issuer signing keys.
//!
//! Each org that has claimed an issuer subdomain signs its OIDC federation
//! tokens with its **own** keys, served only at its own JWKS — so the issuer
//! host is a real cryptographic tenant boundary (a token for org A does not
//! verify against org B's keys). This is generic OIDC issuer isolation, the
//! same property Okta/Auth0/Ory give each tenant; it lets any relying party
//! (AWS STS/Identity Center, GCP/Azure workload identity, Kubernetes, Vault,
//! or a plain OIDC RP) trust the org's issuer without a per-token condition.
//!
//! An org's keys are a **set** ([`OrgKeys`]): one ES256 and one RS256, created
//! and loaded together — a per-org issuer always has both. [`resolve_org_keys`]
//! is the single entry point; callers pick the algorithm they need and fall
//! back to the common platform key when the org has none. The key material is
//! generated by aws-lc-rs (via [`OidcSigningKey`] / [`OidcRsaSigningKey`]) and
//! sealed at rest by the document store.
//!
//! Keys are created on first use, but **only when the document store encrypts
//! at rest** ([`crate::db::store::DocumentStore::is_encrypted`]). In the dev
//! plaintext store no key is created and the resolver returns `None`, so
//! callers fall back to the common key — a private key is never persisted in
//! the clear, and there is no config flag threaded through call sites.

use std::sync::Arc;

use anyhow::{Context, Result};
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use zeroize::Zeroizing;

use axum::http::StatusCode;

use crate::AppState;
use crate::config::ServerConfig;
use crate::db::documents::oauth::JwsAlgorithm;
use crate::db::documents::organization::{OrgSigningKeyDoc, SigningKeyState};
use crate::db::store::DocumentStore;
use crate::db::{self, Organization};
use crate::services::error::ServiceError;

use super::discovery::{JwksResponse, build_jwks};
use super::keys::{Jwk, OidcRsaSigningKey, OidcSigningKey};

/// The issuer an org's federation tokens must use: its claimed subdomain
/// issuer, or the shared base URL when it has no subdomain.
///
/// **Fail-closed:** an org that claimed a subdomain must never fall back to the
/// shared issuer — its tokens would not match its discovery document or the
/// relying party's OIDC provider config. A subdomain that can't be turned into
/// an issuer URL is an error, not a silent downgrade.
///
/// # Errors
/// Returns `ServiceError` if a claimed label can't be built into an issuer URL.
pub fn org_issuer_or_base(
    config: &ServerConfig,
    org: Option<&Organization>,
) -> Result<String, ServiceError> {
    if let Some(label) = org.and_then(|o| o.subdomain.as_deref()) {
        config.org_issuer(label).ok_or_else(|| {
            tracing::error!("could not build org issuer for label '{label}' from base_url");
            ServiceError::api(
                StatusCode::INTERNAL_SERVER_ERROR,
                "issuer_error",
                "Failed to construct the organization issuer",
            )
        })
    } else {
        Ok(config.base_url.clone())
    }
}

/// An org's own issuer signing keys — one per algorithm, created and loaded as
/// a set. Callers project the field they need (`&keys.es256` / `&keys.rs256`).
pub struct OrgKeys {
    pub es256: OidcSigningKey,
    pub rs256: OidcRsaSigningKey,
}

/// Resolve an org's own signing key set, creating it on first use.
///
/// Returns `None` when the org has no claimed subdomain, or when the document
/// store doesn't encrypt at rest (dev) — the caller then falls back to the
/// common platform key. Held in an `Arc` so a request keeps the set cheaply.
///
/// # Errors
/// Returns an error if key creation or loading fails.
pub async fn resolve_org_keys(
    state: &Arc<AppState>,
    org: Option<&Organization>,
) -> Result<Option<Arc<OrgKeys>>> {
    let Some(org) = org else { return Ok(None) };
    if org.subdomain.is_none() || !state.store.is_encrypted() {
        return Ok(None);
    }
    let store = &state.store;
    ensure_key::<OidcSigningKey>(store, &org.id).await?;
    ensure_key::<OidcRsaSigningKey>(store, &org.id).await?;
    let (Some(es256), Some(rs256)) = (
        load_key::<OidcSigningKey>(store, &org.id).await?,
        load_key::<OidcRsaSigningKey>(store, &org.id).await?,
    ) else {
        return Ok(None);
    };
    Ok(Some(Arc::new(OrgKeys { es256, rs256 })))
}

/// Build the JWKS served on `org`'s issuer-subdomain host: the org's own keys,
/// or the common keys when the org has none (dev / not-yet-encrypted). RSA
/// first (OIDC Core §3.1.3.7), then EC.
///
/// # Errors
/// Returns `ServiceError` if a key cannot be resolved or exported.
pub async fn org_jwks(
    state: &Arc<AppState>,
    org: &Organization,
) -> Result<JwksResponse, ServiceError> {
    let Some(keys) = resolve_org_keys(state, Some(org))
        .await
        .map_err(|e| ServiceError::Internal(format!("resolve org keys: {e}")))?
    else {
        return build_jwks(state);
    };
    let export_err = |e: anyhow::Error| ServiceError::Internal(format!("export org JWK: {e}"));
    Ok(JwksResponse {
        keys: vec![
            Jwk::Rsa(keys.rs256.public_key_jwk().map_err(export_err)?),
            Jwk::Ec(keys.es256.public_key_jwk().map_err(export_err)?),
        ],
    })
}

/// A signing-key type that can back a per-org issuer. Lets key creation and
/// loading be written once over both algorithms; the methods forward to the
/// inherent aws-lc-rs–backed constructors.
trait OrgIssuerKey: Sized + 'static {
    const ALG: JwsAlgorithm;
    fn generate_der() -> Result<Zeroizing<Vec<u8>>>;
    fn from_der(der: &[u8]) -> Result<Self>;
    fn kid(&self) -> String;
}

impl OrgIssuerKey for OidcSigningKey {
    const ALG: JwsAlgorithm = JwsAlgorithm::Es256;
    fn generate_der() -> Result<Zeroizing<Vec<u8>>> {
        Self::generate_pkcs8_der()
    }
    fn from_der(der: &[u8]) -> Result<Self> {
        Self::from_pkcs8_der(der)
    }
    fn kid(&self) -> String {
        self.key_id().to_string()
    }
}

impl OrgIssuerKey for OidcRsaSigningKey {
    const ALG: JwsAlgorithm = JwsAlgorithm::Rs256;
    fn generate_der() -> Result<Zeroizing<Vec<u8>>> {
        Self::generate_pkcs8_der()
    }
    fn from_der(der: &[u8]) -> Result<Self> {
        Self::from_pkcs8_der(der)
    }
    fn kid(&self) -> String {
        self.key_id().to_string()
    }
}

/// Create the org's `Active` key for algorithm `K` if it doesn't exist.
///
/// Idempotent: the deterministic slot makes a concurrent creation or retry
/// collide on the primary key rather than insert a duplicate. Keygen runs on
/// the blocking pool (RSA-3072 takes ~200ms).
async fn ensure_key<K: OrgIssuerKey>(store: &DocumentStore, org_id: &str) -> Result<()> {
    if db::get_org_signing_key(store, org_id, K::ALG, SigningKeyState::Active)
        .await?
        .is_some()
    {
        return Ok(());
    }
    let der = tokio::task::spawn_blocking(K::generate_der)
        .await
        .context("key generation task panicked")??;
    let doc = OrgSigningKeyDoc {
        org_id: org_id.to_string(),
        alg: K::ALG,
        state: SigningKeyState::Active,
        kid: K::from_der(&der)?.kid(),
        private_pkcs8_der_b64: STANDARD.encode(&der),
        not_after: None,
    };
    db::try_insert_org_signing_key(store, &doc).await?;
    Ok(())
}

async fn load_key<K: OrgIssuerKey>(store: &DocumentStore, org_id: &str) -> Result<Option<K>> {
    let Some(doc) = db::get_org_signing_key(store, org_id, K::ALG, SigningKeyState::Active).await?
    else {
        return Ok(None);
    };
    let der = STANDARD
        .decode(&doc.data.private_pkcs8_der_b64)
        .context("decode org signing key DER")?;
    Ok(Some(K::from_der(&der)?))
}

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    reason = "test code: panic on assertion failure is acceptable"
)]
mod tests {
    use super::org_issuer_or_base;
    use crate::db::Organization;
    use crate::test_utils::test_config;
    use jiff::Timestamp;

    fn org(subdomain: Option<&str>) -> Organization {
        Organization {
            id: "org1".to_string(),
            domain: "acme.com".to_string(),
            name: None,
            created_at: Timestamp::now(),
            created_by_user_id: None,
            additional_domains: Vec::new(),
            subdomain: subdomain.map(String::from),
        }
    }

    #[test]
    fn issuer_is_org_subdomain_or_base_url() {
        let config = test_config();
        // No org, or an org without a subdomain -> shared base URL.
        assert_eq!(org_issuer_or_base(&config, None).unwrap(), config.base_url);
        assert_eq!(
            org_issuer_or_base(&config, Some(&org(None))).unwrap(),
            config.base_url
        );
        // A claimed subdomain -> the org issuer host.
        assert_eq!(
            org_issuer_or_base(&config, Some(&org(Some("acme")))).unwrap(),
            "https://acme.test.example.com"
        );
    }
}
