// SPDX-License-Identifier: Apache-2.0 OR MIT
//! Per-organization OIDC issuer signing keys and rotation.
//!
//! Each org that has claimed an issuer subdomain signs its OIDC federation
//! tokens with its **own** keys, served only at its own JWKS — so the issuer
//! host is a real cryptographic tenant boundary (a token for org A does not
//! verify against org B's keys). This is generic OIDC issuer isolation, the
//! same property Okta/Auth0/Ory give each tenant; it lets any relying party
//! (AWS STS/Identity Center, GCP/Azure workload identity, Kubernetes, Vault,
//! or a plain OIDC RP) trust the org's issuer without a per-token condition.
//!
//! An org's keys are a **set** ([`OrgKeys`]): one ES256 and one RS256, created
//! and loaded together — a per-org issuer always has both. [`resolve_org_keys`]
//! is the single entry point for signing; callers pick the algorithm they need
//! and fall back to the common platform key when the org has none. The key
//! material is generated by aws-lc-rs (via [`OidcSigningKey`] /
//! [`OidcRsaSigningKey`]) and sealed at rest by the document store.
//!
//! ## Rotation lifecycle
//!
//! An operator triggers rotation via the admin UI (`POST /admin/subdomain/rotate`
//! or the emergency variant). The graceful path:
//!
//! 1. **Stage** (`stage_org_key_rotation`): generates successor keys for both
//!    ES256 and RS256, writes them to the *next* deterministic slots as
//!    [`SigningKeyState::Pending`]. The keys are published in the org JWKS
//!    immediately (relying parties can cache them).
//! 2. **Activate** (cleanup-driven, `try_activate_org_key_rotation`): after
//!    `PUBLISH_AHEAD_HOURS` the cleanup loop promotes the pending key to Active
//!    and demotes the old active key to [`SigningKeyState::Retiring`].
//! 3. **Reap** (cleanup-driven, `reap_org_retired_key`): after the retirement
//!    window the Retiring key is deleted.
//!
//! The emergency path (`emergency_rotate_org_keys`) skips staging: the
//! predecessor is deleted outright and a new Active key takes its place in one
//! transaction. Outstanding tokens signed by the compromised key will fail
//! verification until RPs refetch the JWKS.
//!
//! ## Cache invariant (S1)
//!
//! [`OrgKeysCache`] holds a **unified snapshot** per org: both the active
//! signers (for token issuance) and the ordered public-JWK list (for the JWKS
//! endpoint) are projections of the same `list_all("org_id")` result, so the
//! signing key is always in this instance's own published JWKS. Every rotation
//! transition calls `invalidate(org_id)` so the next request rebuilds from the
//! DB immediately.
//!
//! ## Encryption guard
//!
//! Keys are created on first use, but **only when the document store encrypts
//! at rest** ([`crate::db::store::DocumentStore::is_encrypted`]). In the dev
//! plaintext store no key is created and the resolver returns `None`, so
//! callers fall back to the common key — a private key is never persisted in
//! the clear, and there is no config flag threaded through call sites.

use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use axum::http::StatusCode;
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use jiff::{Span, Timestamp};
use secrecy::ExposeSecret;
use zeroize::Zeroizing;

use crate::AppState;
use crate::config::ServerConfig;
use crate::db::audit::AuditStore;
use crate::db::document_type::Document;
use crate::db::documents::oauth::JwsAlgorithm;
use crate::db::documents::organization::{OrgSigningKeyDoc, SigningKeyState};
use crate::db::store::DocumentStore;
use crate::db::{self, Organization};
use crate::services::error::ServiceError;

use super::discovery::{JwksResponse, build_jwks};
use super::keys::{Jwk, OidcRsaSigningKey, OidcSigningKey};

/// Hours to publish a pending successor key before activating it.
///
/// Fixed at 24h (S2 / user decision): larger than the 1h OIDC discovery
/// `max-age` and well above community-reported AWS JWKS cache TTLs, so relying
/// parties will have seen the new `kid` before signing switches to it.
pub(crate) const PUBLISH_AHEAD_HOURS: i64 = 24;

/// Floor for the retirement window in hours (M1).
///
/// Ensures that a reduction of `session_hours` below 8h before rotation does
/// not leave tokens signed by the old key verifiable for longer than the
/// retirement window covers.
const RETIREMENT_FLOOR_HOURS: i64 = 8;

/// Margin added to the retirement window to absorb cache staleness.
///
/// Covers the `ORG_KEYS_CACHE_TTL` (60s) and the OIDC discovery `max-age`
/// (1h), plus a conservative buffer. The window formula is:
/// `activate_at + max(session_hours, RETIREMENT_FLOOR_HOURS) + RETIREMENT_MARGIN_HOURS`.
const RETIREMENT_MARGIN_HOURS: i64 = 2;

/// The issuer an org's federation tokens must use: its claimed subdomain
/// issuer, or the shared base URL when it has no subdomain.
///
/// **Fail-closed:** an org that claimed a subdomain must never fall back to the
/// shared issuer — its tokens would not match its discovery document or the
/// relying party's OIDC provider config. A subdomain that can't be turned into
/// an issuer URL is an error, not a silent downgrade.
///
/// Issuer selection is gated on whether a subdomain is *claimed*, not on
/// at-rest encryption — unlike [`resolve_org_keys`], which yields a per-org
/// signing key only under encryption. These stay consistent because claiming
/// requires an encrypted store (enforced at the claim handler and the startup
/// guard) and `is_encrypted()` is fixed for the life of the process: a claimed
/// subdomain therefore implies per-org keys exist, so the org issuer is always
/// backed by an org-specific key. The one exception — org issuer served under
/// the shared key — requires an out-of-band DB write on a plaintext deployment;
/// [`resolve_org_keys`]'s encryption check is the fail-safe backstop for it.
///
/// # Errors
/// Returns `ServiceError` if a claimed label can't be built into an issuer URL.
pub fn org_issuer_or_base(
    config: &ServerConfig,
    org: Option<&Organization>,
) -> Result<String, ServiceError> {
    if let Some(label) = org.and_then(|o| o.subdomain.as_deref()) {
        config.org_issuer(label).ok_or_else(|| {
            tracing::error!("could not build org issuer for label '{label}' from base_url");
            ServiceError::api(
                StatusCode::INTERNAL_SERVER_ERROR,
                "issuer_error",
                "Failed to construct the organization issuer",
            )
        })
    } else {
        Ok(config.base_url.clone())
    }
}

/// An org's active signing keys — one per algorithm.
///
/// Callers project the field they need (`&keys.es256` / `&keys.rs256`).
pub struct OrgKeys {
    pub es256: OidcSigningKey,
    pub rs256: OidcRsaSigningKey,
}

/// A unified snapshot of an org's full key set, held by [`OrgKeysCache`].
///
/// Both projections (signing and JWKS) derive from the same `list_all("org_id")`
/// result, so the signing key is always in this instance's own published JWKS —
/// no cross-projection staleness within a single server instance (S1 invariant).
pub struct OrgKeySetSnapshot {
    /// Active signers for token issuance — ES256 and RS256.
    pub signers: OrgKeys,
    /// Ordered public JWKs for all live keys (Active + Pending + Retiring).
    ///
    /// Sorted per M2: all RS256 keys first (Active → Pending → Retiring),
    /// then all ES256 keys in the same order. Per OIDC Core §3.1.3.7 RS256
    /// must appear first; within an algorithm the order is deterministic for
    /// stable response bytes and test assertions.
    pub jwks: Vec<Jwk>,
}

/// How long a resolved key set may be served from [`OrgKeysCache`].
const ORG_KEYS_CACHE_TTL: Duration = Duration::from_mins(1);

/// Inner map type for `OrgKeysCache`: org ID → (insert time, snapshot).
type OrgKeysCacheMap = HashMap<String, (Instant, Arc<OrgKeySetSnapshot>)>;

/// Cache of resolved per-org key set snapshots, keyed by org ID.
///
/// The inner `Arc<Mutex<…>>` makes `OrgKeysCache` cheaply cloneable: the
/// background cleanup task and request handlers share the same underlying map
/// so cache invalidations propagate across both.
///
/// Every rotation transition must call `invalidate(org_id)` so the next
/// request after a state change rebuilds from the DB rather than serving a
/// stale snapshot.
#[derive(Default)]
pub struct OrgKeysCache {
    entries: Arc<Mutex<OrgKeysCacheMap>>,
}

impl Clone for OrgKeysCache {
    fn clone(&self) -> Self {
        Self {
            entries: Arc::clone(&self.entries),
        }
    }
}

impl OrgKeysCache {
    /// Return a cached snapshot for `org_id`, if present and not expired.
    fn get(&self, org_id: &str) -> Option<Arc<OrgKeySetSnapshot>> {
        let Ok(map) = self.entries.lock() else {
            return None;
        };
        map.get(org_id)
            .filter(|(inserted_at, _)| inserted_at.elapsed() < ORG_KEYS_CACHE_TTL)
            .map(|(_, snap)| Arc::clone(snap))
    }

    /// Cache `snapshot`, pruning expired entries so deleted orgs don't accumulate.
    fn insert(&self, org_id: &str, snapshot: Arc<OrgKeySetSnapshot>) {
        let Ok(mut map) = self.entries.lock() else {
            return;
        };
        map.retain(|_, (inserted_at, _)| inserted_at.elapsed() < ORG_KEYS_CACHE_TTL);
        map.insert(org_id.to_string(), (Instant::now(), snapshot));
    }

    /// Evict the cached snapshot for `org_id`.
    ///
    /// Called after every rotation transition (stage, activate, reap, emergency)
    /// so the next request rebuilds from the DB immediately rather than serving
    /// a now-stale snapshot.
    pub fn invalidate(&self, org_id: &str) {
        if let Ok(mut map) = self.entries.lock() {
            map.remove(org_id);
        }
    }
}

/// Resolve an org's own signing key set, creating it on first use.
///
/// Returns `None` when the org has no claimed subdomain, or when the document
/// store doesn't encrypt at rest — the caller then falls back to the common
/// platform key. Resolutions are served from a per-org cache for
/// [`ORG_KEYS_CACHE_TTL`], so the token hot paths don't re-read and unseal key
/// rows on every request.
///
/// The returned snapshot also contains the ordered public-JWK list for all live
/// keys (Active + Pending + Retiring) which [`org_jwks`] uses directly.
///
/// # Errors
/// Returns an error if key creation or loading fails.
pub async fn resolve_org_keys(
    state: &Arc<AppState>,
    org: Option<&Organization>,
) -> Result<Option<Arc<OrgKeySetSnapshot>>> {
    let Some(org) = org else { return Ok(None) };
    if org.subdomain.is_none() || !state.store.is_encrypted() {
        return Ok(None);
    }
    if let Some(snap) = state.org_keys_cache.get(&org.id) {
        return Ok(Some(snap));
    }
    let store = &state.store;

    // Single list_all call to check which active keys already exist (P8 —
    // avoids 3 serial round-trips by discovering the full doc set upfront).
    let docs = db::list_org_signing_keys(store, &org.id).await?;
    let needs_es256 = !docs
        .iter()
        .any(|d| d.data.alg == JwsAlgorithm::Es256 && d.data.state == SigningKeyState::Active);
    let needs_rs256 = !docs
        .iter()
        .any(|d| d.data.alg == JwsAlgorithm::Rs256 && d.data.state == SigningKeyState::Active);

    if needs_es256 {
        ensure_es256_key(store, &org.id).await?;
    }
    if needs_rs256 {
        ensure_rs256_key(store, &org.id).await?;
    }

    // Re-read only when we just generated new keys; otherwise build from the
    // already-loaded list (saves the third round-trip in the common case).
    let docs = if needs_es256 || needs_rs256 {
        db::list_org_signing_keys(store, &org.id).await?
    } else {
        docs
    };

    let Some(snap) = build_snapshot(&docs)? else {
        return Ok(None);
    };
    let snap = Arc::new(snap);
    state.org_keys_cache.insert(&org.id, Arc::clone(&snap));
    Ok(Some(snap))
}

/// Build the JWKS served on `org`'s issuer-subdomain host: the org's own keys,
/// or the common keys when the org has none (dev / not-yet-encrypted). RSA
/// first (OIDC Core §3.1.3.7), then EC; within each alg: Active → Pending →
/// Retiring.
///
/// Uses the unified cache snapshot so signing and JWKS are always consistent
/// within an instance (S1 invariant).
///
/// # Errors
/// Returns `ServiceError` if a key cannot be resolved or exported.
pub async fn org_jwks(
    state: &Arc<AppState>,
    org: &Organization,
) -> Result<JwksResponse, ServiceError> {
    let Some(snap) = resolve_org_keys(state, Some(org))
        .await
        .map_err(|e| ServiceError::Internal(format!("resolve org keys: {e}")))?
    else {
        return build_jwks(state);
    };
    Ok(JwksResponse {
        keys: snap.jwks.clone(),
    })
}

/// Create the org's ES256 key if it doesn't exist (current slot).
///
/// Idempotent: the deterministic slot makes a concurrent creation or retry
/// collide on the primary key rather than insert a duplicate.
async fn ensure_es256_key(store: &DocumentStore, org_id: &str) -> Result<()> {
    if db::get_org_signing_key(store, org_id, JwsAlgorithm::Es256)
        .await?
        .is_some()
    {
        return Ok(());
    }
    let der = OidcSigningKey::generate_pkcs8_der().context("ensure ES256: generate DER")?;
    let key = OidcSigningKey::from_pkcs8_der(&der).context("ensure ES256: parse DER")?;
    let doc = OrgSigningKeyDoc {
        org_id: org_id.to_string(),
        alg: JwsAlgorithm::Es256,
        kid: key.key_id().to_string(),
        private_pkcs8_der_b64: STANDARD.encode(&der).into(),
        state: SigningKeyState::Active,
    };
    db::try_insert_org_signing_key(store, &doc).await?;
    Ok(())
}

/// Create the org's RS256 key if it doesn't exist (current slot).
///
/// Offloads RSA-3072 generation (~200ms) to the blocking pool. Idempotent.
async fn ensure_rs256_key(store: &DocumentStore, org_id: &str) -> Result<()> {
    if db::get_org_signing_key(store, org_id, JwsAlgorithm::Rs256)
        .await?
        .is_some()
    {
        return Ok(());
    }
    let der = tokio::task::spawn_blocking(OidcRsaSigningKey::generate_pkcs8_der)
        .await
        .context("ensure RS256: keygen task panicked")??;
    let key = OidcRsaSigningKey::from_pkcs8_der(&der).context("ensure RS256: parse DER")?;
    let doc = OrgSigningKeyDoc {
        org_id: org_id.to_string(),
        alg: JwsAlgorithm::Rs256,
        kid: key.key_id().to_string(),
        private_pkcs8_der_b64: STANDARD.encode(&der).into(),
        state: SigningKeyState::Active,
    };
    db::try_insert_org_signing_key(store, &doc).await?;
    Ok(())
}

/// Decode the DER from an `OrgSigningKeyDoc` into a `Zeroizing<Vec<u8>>`.
fn decode_der(doc: &OrgSigningKeyDoc) -> Result<Zeroizing<Vec<u8>>> {
    Ok(Zeroizing::new(
        STANDARD
            .decode(doc.private_pkcs8_der_b64.expose_secret())
            .context("decode org signing key DER")?,
    ))
}

/// State-priority ordering used for JWKS sort within an algorithm.
fn state_priority(state: &SigningKeyState) -> u8 {
    match state {
        SigningKeyState::Active => 0,
        SigningKeyState::Pending { .. } => 1,
        SigningKeyState::Retiring { .. } => 2,
    }
}

/// Build a unified [`OrgKeySetSnapshot`] from a pre-loaded slice of key docs.
///
/// Finds the Active ES256 and RS256 keys for signing, and builds the sorted
/// public-JWK list for the JWKS endpoint. Returns `None` if no Active key is
/// found for either algorithm.
///
/// **Ordering (M2):** RS256 keys first, then ES256; within each algorithm:
/// Active → Pending → Retiring. This is a hard constraint for OIDC Core
/// §3.1.3.7 compliance (RS256 must appear first).
///
/// Takes pre-loaded docs from the caller (P8 — avoids an extra DB round-trip
/// when `resolve_org_keys` already has the full doc list in hand).
fn build_snapshot(docs: &[Document<OrgSigningKeyDoc>]) -> Result<Option<OrgKeySetSnapshot>> {
    // Separate by alg and sort by state priority within each alg.
    let mut rs256_docs: Vec<_> = docs
        .iter()
        .filter(|d| d.data.alg == JwsAlgorithm::Rs256)
        .collect();
    let mut es256_docs: Vec<_> = docs
        .iter()
        .filter(|d| d.data.alg == JwsAlgorithm::Es256)
        .collect();
    rs256_docs.sort_by_key(|d| state_priority(&d.data.state));
    es256_docs.sort_by_key(|d| state_priority(&d.data.state));

    // Find the active key for each alg — no active key means the org has no
    // live signing capability; return None to fall back to the common key.
    let Some(active_rs256_doc) = rs256_docs
        .iter()
        .find(|d| d.data.state == SigningKeyState::Active)
    else {
        return Ok(None);
    };
    let Some(active_es256_doc) = es256_docs
        .iter()
        .find(|d| d.data.state == SigningKeyState::Active)
    else {
        return Ok(None);
    };

    let rs256_der = decode_der(&active_rs256_doc.data)?;
    let es256_der = decode_der(&active_es256_doc.data)?;
    let rs256 = OidcRsaSigningKey::from_pkcs8_der(&rs256_der)?;
    let es256 = OidcSigningKey::from_pkcs8_der(&es256_der)?;

    // Build public JWKs: RS256 first (all states), then ES256 (all states).
    let mut jwks = Vec::with_capacity(rs256_docs.len().saturating_add(es256_docs.len()));
    for doc in &rs256_docs {
        let der = decode_der(&doc.data)?;
        let key = OidcRsaSigningKey::from_pkcs8_der(&der)?;
        jwks.push(Jwk::Rsa(key.public_key_jwk()?));
    }
    for doc in &es256_docs {
        let der = decode_der(&doc.data)?;
        let key = OidcSigningKey::from_pkcs8_der(&der)?;
        jwks.push(Jwk::Ec(key.public_key_jwk()?));
    }

    Ok(Some(OrgKeySetSnapshot {
        signers: OrgKeys { es256, rs256 },
        jwks,
    }))
}

// ---------------------------------------------------------------------------
// Rotation error type (follows OrgCasError pattern, per N3)
// ---------------------------------------------------------------------------

/// Error type for rotation operations that may be OCC-retried.
///
/// `OccConflict` maps to `with_dsql_retry!`'s retry path; `Other` delegates to
/// `is_retryable_db_error` so that DSQL commit-abort errors (which surface as
/// `anyhow::Error` rather than `compare_and_update → false`) also retry.
#[derive(Debug, thiserror::Error)]
pub(crate) enum OrgRotationError {
    /// Application-level CAS version conflict (`compare_and_update` returned
    /// `false`). Retried by `with_dsql_retry!`.
    #[error("org signing-key slot was modified concurrently; retrying")]
    OccConflict,
    /// Business rejection or infrastructure failure. Not retried unless the
    /// wrapped error carries a retryable DB error code (e.g. DSQL commit-abort).
    #[error(transparent)]
    Other(#[from] anyhow::Error),
}

impl crate::db::pool::RetryableError for OrgRotationError {
    fn is_retryable(&self) -> bool {
        match self {
            Self::OccConflict => true,
            Self::Other(e) => crate::db::pool::is_retryable_db_error(e),
        }
    }
}

// ---------------------------------------------------------------------------
// Typed activation outcome (S3)
// ---------------------------------------------------------------------------

/// Result of a single `try_activate_org_key_rotation` attempt for one `(org,
/// alg)` pair.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ActivateOutcome {
    /// Signing switched: `old_kid` is now Retiring, `new_kid` is now Active.
    Activated { old_kid: String, new_kid: String },
    /// A peer instance already completed this activation; nothing to do.
    AlreadyDone,
    /// The pending key's `activate_at` has not yet elapsed.
    NotDue,
    /// No pending key is staged for this `(org, alg)` pair.
    NothingStaged,
}

// ---------------------------------------------------------------------------
// Graceful rotation — stage
// ---------------------------------------------------------------------------

/// Stage a graceful key rotation for an organization.
///
/// Generates successor keys for **both** ES256 and RS256 (N1 — a key-store
/// compromise exposes both DERs), writes them to the next-slot with state
/// [`SigningKeyState::Pending`] and `activate_at = now + PUBLISH_AHEAD_HOURS`,
/// and publishes them immediately in the org JWKS so relying parties can cache
/// the new `kid` before signing switches.
///
/// Idempotent: if both next-slots already exist, returns `Ok(false)` without
/// emitting any DB writes. Returns `Ok(true)` when at least one new key was
/// staged. Callers can use the bool to suppress a redundant audit event when the
/// operator clicks "Rotate" while a rotation is already in progress (C6).
///
/// Invalidates the org's cache entry so the next JWKS response includes the
/// new Pending keys without waiting for the 60s TTL (I3 / S1 invariant).
///
/// # Errors
/// Returns an error if key generation or the DB insert fails.
pub async fn stage_org_key_rotation(
    store: &DocumentStore,
    org_id: &str,
    cache: &OrgKeysCache,
) -> Result<bool> {
    // Check next-slot occupancy before generating keys (L2 / S1).
    // RSA-3072 keygen takes ~200ms on the blocking pool; skip it when the
    // slot is already occupied. This is a courtesy check — `stage_one_alg`
    // is still idempotent if a concurrent writer races between the read and
    // the insert: the no-op `try_insert_org_signing_key_next` absorbs it.
    let es256_occupied = db::get_org_signing_key_next(store, org_id, JwsAlgorithm::Es256)
        .await?
        .is_some();
    let rs256_occupied = db::get_org_signing_key_next(store, org_id, JwsAlgorithm::Rs256)
        .await?
        .is_some();

    if es256_occupied && rs256_occupied {
        // Both pending — already staged; invalidate in case the cache is stale.
        cache.invalidate(org_id);
        return Ok(false);
    }

    // Generate only the missing key material.
    let rs256_der = if !rs256_occupied {
        Some(
            tokio::task::spawn_blocking(OidcRsaSigningKey::generate_pkcs8_der)
                .await
                .context("stage: RS256 keygen task panicked")??,
        )
    } else {
        None
    };
    let es256_der = if !es256_occupied {
        Some(OidcSigningKey::generate_pkcs8_der().context("stage: ES256 keygen")?)
    } else {
        None
    };

    // On a partial-failure retry (ES256 staged, RS256 failed or vice versa),
    // reuse the already-staged alg's activate_at so both algs activate together
    // (C2 — preserves N1 atomicity intent on retry). Fall back to now +
    // PUBLISH_AHEAD_HOURS when neither slot is occupied (the common case).
    let activate_at = if es256_occupied {
        // ES256 is staged — read its activate_at to sync RS256.
        db::get_org_signing_key_next(store, org_id, JwsAlgorithm::Es256)
            .await?
            .and_then(|d| {
                if let SigningKeyState::Pending { activate_at } = d.data.state {
                    Some(activate_at)
                } else {
                    None
                }
            })
            .unwrap_or_else(|| {
                Timestamp::now()
                    .checked_add(Span::new().hours(PUBLISH_AHEAD_HOURS))
                    .unwrap_or_else(|_| Timestamp::now())
            })
    } else if rs256_occupied {
        // RS256 is staged — read its activate_at to sync ES256.
        db::get_org_signing_key_next(store, org_id, JwsAlgorithm::Rs256)
            .await?
            .and_then(|d| {
                if let SigningKeyState::Pending { activate_at } = d.data.state {
                    Some(activate_at)
                } else {
                    None
                }
            })
            .unwrap_or_else(|| {
                Timestamp::now()
                    .checked_add(Span::new().hours(PUBLISH_AHEAD_HOURS))
                    .unwrap_or_else(|_| Timestamp::now())
            })
    } else {
        Timestamp::now()
            .checked_add(Span::new().hours(PUBLISH_AHEAD_HOURS))
            .context("stage: activate_at timestamp overflow")?
    };

    if let Some(ref der) = es256_der {
        stage_one_alg(store, org_id, JwsAlgorithm::Es256, der, activate_at).await?;
    }
    if let Some(ref der) = rs256_der {
        stage_one_alg(store, org_id, JwsAlgorithm::Rs256, der, activate_at).await?;
    }

    // Invalidate so the next JWKS response immediately includes the Pending keys.
    cache.invalidate(org_id);
    Ok(true)
}

/// Stage one algorithm's successor key in the next-slot for `org_id`.
///
/// Called twice by [`stage_org_key_rotation`] (ES256 then RS256). Idempotent:
/// `try_insert_org_signing_key_next` silently skips if the slot already exists.
async fn stage_one_alg(
    store: &DocumentStore,
    org_id: &str,
    alg: JwsAlgorithm,
    der: &[u8],
    activate_at: Timestamp,
) -> Result<()> {
    let kid = match alg {
        JwsAlgorithm::Es256 => OidcSigningKey::from_pkcs8_der(der)
            .context("stage ES256: parse DER")?
            .key_id()
            .to_string(),
        JwsAlgorithm::Rs256 => OidcRsaSigningKey::from_pkcs8_der(der)
            .context("stage RS256: parse DER")?
            .key_id()
            .to_string(),
        other => anyhow::bail!("stage_one_alg: unsupported algorithm {other:?}"),
    };
    let doc = OrgSigningKeyDoc {
        org_id: org_id.to_string(),
        alg,
        kid,
        private_pkcs8_der_b64: STANDARD.encode(der).into(),
        state: SigningKeyState::Pending { activate_at },
    };
    db::try_insert_org_signing_key_next(store, &doc).await?;
    Ok(())
}

// ---------------------------------------------------------------------------
// Graceful rotation — activate (S3 pseudocode)
// ---------------------------------------------------------------------------

/// Try to activate a staged key rotation for one `(org_id, alg)` pair.
///
/// Implements the CAS-first OCC pattern from the rev-B spec (S3): every
/// terminal branch returns `Ok(..)` *before* any write, and CAS-loss is the
/// only `Err(OccConflict)` exit. This prevents `with_dsql_retry!` from spinning
/// on an already-completed activation.
///
/// DSQL commit-abort errors surface through `OrgRotationError::Other`; the
/// `RetryableError` impl delegates to `is_retryable_db_error` so they also
/// loop (N3).
pub(crate) async fn try_activate_org_key_rotation(
    store: &DocumentStore,
    org_id: &str,
    alg: JwsAlgorithm,
    session_hours: u64,
) -> Result<ActivateOutcome, OrgRotationError> {
    crate::with_dsql_retry!(async {
        let mut tx = store.begin().await?;

        // ---- terminal short-circuits: decided BEFORE any write, return Ok(..) ----

        let next_id = db::deterministic_org_key_next_id(org_id, alg);
        let Some(next_doc) = tx.get::<OrgSigningKeyDoc>(&next_id).await? else {
            // No staged key (or already consumed by a peer instance).
            return Ok(ActivateOutcome::NothingStaged);
        };

        let SigningKeyState::Pending { activate_at } = next_doc.data.state else {
            // Staged key is not in Pending state (shouldn't happen in well-formed DB).
            return Ok(ActivateOutcome::AlreadyDone);
        };

        if activate_at > Timestamp::now() {
            return Ok(ActivateOutcome::NotDue);
        }

        let current_id = db::deterministic_org_key_id(org_id, alg);
        let Some(current_doc) = tx.get::<OrgSigningKeyDoc>(&current_id).await? else {
            // No active key; treat as already done (shouldn't happen).
            return Ok(ActivateOutcome::AlreadyDone);
        };

        // If the previous slot is occupied, another activation is still in its
        // retirement window — treat as done and let reaping clear the predecessor.
        let prev_id = db::deterministic_org_key_previous_id(org_id, alg);
        if tx.get::<OrgSigningKeyDoc>(&prev_id).await?.is_some() {
            return Ok(ActivateOutcome::AlreadyDone);
        }

        // Capture predecessor material BEFORE the CAS overwrites the current slot.
        let old_kid = current_doc.data.kid.clone();
        let new_kid = next_doc.data.kid.clone();
        let current_version = current_doc.version;

        // Compute retirement window (M1): floor at RETIREMENT_FLOOR_HOURS so a
        // session_hours reduction before rotation doesn't under-cover existing tokens.
        let session_h = i64::try_from(session_hours).unwrap_or(RETIREMENT_FLOOR_HOURS);
        let retire_hours = session_h.max(RETIREMENT_FLOOR_HOURS);
        let not_after = activate_at
            .checked_add(Span::new().hours(retire_hours.saturating_add(RETIREMENT_MARGIN_HOURS)))
            .map_err(|e| OrgRotationError::Other(anyhow::Error::new(e)))?;

        // Build the new Active doc (successor content, Active state).
        let new_active = OrgSigningKeyDoc {
            state: SigningKeyState::Active,
            ..next_doc.data.clone()
        };
        // Build the Retiring doc (predecessor content, Retiring state).
        let retiring = OrgSigningKeyDoc {
            state: SigningKeyState::Retiring { not_after },
            ..current_doc.data.clone()
        };

        // ---- CAS is the single serialization gate; losers stop here ----
        if !tx
            .compare_and_update(&current_id, current_version, &new_active)
            .await?
        {
            // Version bumped by a peer: retry → re-read → NothingStaged / AlreadyDone.
            return Err(OrgRotationError::OccConflict);
        }

        // Sole winner past this point: prev was confirmed absent, so the insert
        // cannot collide with a concurrent activation (CAS-first ordering).
        tx.insert_with_id(&prev_id, &retiring).await?;
        tx.delete(&next_id).await?;

        tx.commit().await.map_err(OrgRotationError::Other)?;

        Ok(ActivateOutcome::Activated { old_kid, new_kid })
    })
}

// ---------------------------------------------------------------------------
// Graceful rotation — reap
// ---------------------------------------------------------------------------

/// Reap an expired Retiring key for one `(org_id, alg)` pair.
///
/// Deletes the previous-slot document if it exists and its `not_after` has
/// elapsed. Emits an `org_issuer_key_reaped` audit event. Invalidates the cache
/// so the deleted key is no longer served in the JWKS.
///
/// Returns `true` if a key was reaped, `false` if the slot was empty or not yet
/// due.
///
/// # Errors
/// Returns an error if the DB delete fails.
pub(crate) async fn reap_org_retired_key(
    store: &DocumentStore,
    org_id: &str,
    alg: JwsAlgorithm,
    audit: &AuditStore,
    cache: &OrgKeysCache,
) -> Result<bool> {
    let prev_id = db::deterministic_org_key_previous_id(org_id, alg);
    let Some(doc) = store.get::<OrgSigningKeyDoc>(&prev_id).await? else {
        return Ok(false);
    };
    let SigningKeyState::Retiring { not_after } = doc.data.state else {
        return Ok(false);
    };
    if not_after > Timestamp::now() {
        return Ok(false);
    }

    let reaped_kid = doc.data.kid.clone();
    store.delete(&prev_id).await?;
    cache.invalidate(org_id);

    let event = serde_json::json!({
        "action": "reap_org_issuer_key",
        "org_id": org_id,
        "alg": alg.as_str(),
        "kid": reaped_kid,
    });
    if let Err(e) = audit
        .insert_event("org_issuer_key_reaped", None, None, &event.to_string())
        .await
    {
        tracing::warn!(error = %e, "failed to write org_issuer_key_reaped audit event");
    }
    Ok(true)
}

// ---------------------------------------------------------------------------
// Cleanup loop — process all pending transitions (M3)
// ---------------------------------------------------------------------------

/// Process pending key-rotation activations and reapings for all organizations.
///
/// Called from the background cleanup loop. Scans all signing-key documents,
/// then for each org:
/// - Activates any Pending keys whose `activate_at` has elapsed (both algs).
/// - Reaps any Retiring keys whose `not_after` has elapsed (both algs).
///
/// Uses `session_hours` from the config to compute the retirement window (M1).
///
/// Per-org failures are logged and skipped so one bad org doesn't abort the
/// whole pass.
///
/// # Errors
/// Returns an error only if the initial scan fails.
pub async fn process_pending_org_key_transitions(
    store: &DocumentStore,
    audit: &AuditStore,
    cache: &OrgKeysCache,
    session_hours: u64,
) -> Result<()> {
    let all_docs = store.list_all::<OrgSigningKeyDoc>().await?;
    let now = Timestamp::now();

    let mut pending_due: Vec<(String, JwsAlgorithm)> = Vec::new();
    let mut retiring_due: Vec<(String, JwsAlgorithm)> = Vec::new();

    for doc in &all_docs {
        match &doc.data.state {
            SigningKeyState::Pending { activate_at } if *activate_at <= now => {
                pending_due.push((doc.data.org_id.clone(), doc.data.alg));
            }
            SigningKeyState::Retiring { not_after } if *not_after <= now => {
                retiring_due.push((doc.data.org_id.clone(), doc.data.alg));
            }
            _ => {}
        }
    }

    for (org_id, alg) in pending_due {
        // try_activate_org_key_rotation contains its own with_dsql_retry! loop.
        match try_activate_org_key_rotation(store, &org_id, alg, session_hours).await {
            Ok(ActivateOutcome::Activated { old_kid, new_kid }) => {
                cache.invalidate(&org_id);
                tracing::info!(
                    org_id,
                    alg = alg.as_str(),
                    old_kid,
                    new_kid,
                    "activated org issuer key"
                );
                let event = serde_json::json!({
                    "action": "activate_org_issuer_key",
                    "org_id": org_id,
                    "alg": alg.as_str(),
                    "old_kid": old_kid,
                    "new_kid": new_kid,
                });
                if let Err(e) = audit
                    .insert_event("org_issuer_key_activated", None, None, &event.to_string())
                    .await
                {
                    tracing::warn!(
                        error = %e,
                        "failed to write org_issuer_key_activated audit event"
                    );
                }
            }
            Ok(_) => {} // NothingStaged / AlreadyDone / NotDue — silent
            Err(e) => {
                tracing::warn!(
                    error = %e,
                    org_id,
                    alg = alg.as_str(),
                    "failed to activate org issuer key"
                );
            }
        }
    }

    for (org_id, alg) in retiring_due {
        if let Err(e) = reap_org_retired_key(store, &org_id, alg, audit, cache).await {
            tracing::warn!(
                error = %e,
                org_id,
                alg = alg.as_str(),
                "failed to reap retired org issuer key"
            );
        }
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Emergency rotation (S4)
// ---------------------------------------------------------------------------

/// Emergency key rotation for an organization.
///
/// Rotates **both** ES256 and RS256 in a **single atomic transaction**.
/// Both successors are generated outside the retry loop (RSA keygen takes
/// ~200ms). If either CAS fails the entire transaction retries atomically;
/// there is no partial-rotation window where one alg is rotated and the other
/// is not.
///
/// The cache is invalidated only after the transaction commits, so this instance
/// never serves a stale snapshot of a key that was already rotated in the DB.
/// If the function returns `Err` (retry budget exhausted), the DB is unchanged
/// and the cache is unmodified.
///
/// Outstanding tokens signed by the compromised key will fail verification until
/// relying parties refetch the JWKS (cross-instance ≤ 60s, downstream ≤ 1h).
/// This breakage is accepted (Q3).
///
/// # Errors
/// Returns an error if key generation or the DB operation fails after the retry
/// budget is exhausted.
pub async fn emergency_rotate_org_keys(
    store: &DocumentStore,
    org_id: &str,
    audit: &AuditStore,
    cache: &OrgKeysCache,
    user_id: Option<&str>,
    email: Option<&str>,
) -> Result<()> {
    // Generate both successors OUTSIDE the retry loop (N4).
    let rs256_der = tokio::task::spawn_blocking(OidcRsaSigningKey::generate_pkcs8_der)
        .await
        .context("emergency: RS256 keygen task panicked")??;
    let es256_der = OidcSigningKey::generate_pkcs8_der().context("emergency: ES256 keygen")?;

    // Parse kids outside the retry loop — cheap and deterministic from the DER.
    let es256_kid = OidcSigningKey::from_pkcs8_der(&es256_der)
        .context("emergency ES256: parse kid")?
        .key_id()
        .to_string();
    let rs256_kid = OidcRsaSigningKey::from_pkcs8_der(&rs256_der)
        .context("emergency RS256: parse kid")?
        .key_id()
        .to_string();

    // Single retry loop: both algs in one transaction — atomicity across algs (I1).
    let result: Result<(String, String), OrgRotationError> = crate::with_dsql_retry!(async {
        let mut tx = store.begin().await?;

        // Read and CAS the ES256 current slot.
        let es256_current_id = db::deterministic_org_key_id(org_id, JwsAlgorithm::Es256);
        let Some(es256_current) = tx.get::<OrgSigningKeyDoc>(&es256_current_id).await? else {
            return Err(OrgRotationError::Other(anyhow::anyhow!(
                "emergency: no current ES256 key for org '{org_id}'"
            )));
        };
        let old_es256_kid = es256_current.data.kid.clone();
        let es256_version = es256_current.version;

        // Read and CAS the RS256 current slot.
        let rs256_current_id = db::deterministic_org_key_id(org_id, JwsAlgorithm::Rs256);
        let Some(rs256_current) = tx.get::<OrgSigningKeyDoc>(&rs256_current_id).await? else {
            return Err(OrgRotationError::Other(anyhow::anyhow!(
                "emergency: no current RS256 key for org '{org_id}'"
            )));
        };
        let old_rs256_kid = rs256_current.data.kid.clone();
        let rs256_version = rs256_current.version;

        // Build replacement Active docs.
        let new_es256 = OrgSigningKeyDoc {
            org_id: org_id.to_string(),
            alg: JwsAlgorithm::Es256,
            kid: es256_kid.clone(),
            private_pkcs8_der_b64: STANDARD.encode(&*es256_der).into(),
            state: SigningKeyState::Active,
        };
        let new_rs256 = OrgSigningKeyDoc {
            org_id: org_id.to_string(),
            alg: JwsAlgorithm::Rs256,
            kid: rs256_kid.clone(),
            private_pkcs8_der_b64: STANDARD.encode(&*rs256_der).into(),
            state: SigningKeyState::Active,
        };

        // CAS both slots. Either version mismatch retries the whole transaction.
        if !tx
            .compare_and_update(&es256_current_id, es256_version, &new_es256)
            .await?
        {
            return Err(OrgRotationError::OccConflict);
        }
        if !tx
            .compare_and_update(&rs256_current_id, rs256_version, &new_rs256)
            .await?
        {
            return Err(OrgRotationError::OccConflict);
        }

        // Delete side slots for both algs outright (S4) — removes compromised key
        // material from the JWKS build immediately after this commit.
        tx.delete(&db::deterministic_org_key_previous_id(
            org_id,
            JwsAlgorithm::Es256,
        ))
        .await?;
        tx.delete(&db::deterministic_org_key_next_id(
            org_id,
            JwsAlgorithm::Es256,
        ))
        .await?;
        tx.delete(&db::deterministic_org_key_previous_id(
            org_id,
            JwsAlgorithm::Rs256,
        ))
        .await?;
        tx.delete(&db::deterministic_org_key_next_id(
            org_id,
            JwsAlgorithm::Rs256,
        ))
        .await?;

        tx.commit().await.map_err(OrgRotationError::Other)?;

        Ok((old_es256_kid, old_rs256_kid))
    });

    let (old_es256_kid, old_rs256_kid) = result.map_err(anyhow::Error::from)?;

    // Invalidate cache after the atomic transaction commits — both algs rotated.
    cache.invalidate(org_id);

    // Emit one audit event per algorithm. Including operator identity (user_id /
    // email) here makes the per-alg events the sole canonical audit trail for an
    // emergency rotation — no separate handler-level event is needed (C1).
    let es256_event = serde_json::json!({
        "action": "emergency_rotate_org_issuer_key",
        "org_id": org_id,
        "alg": JwsAlgorithm::Es256.as_str(),
        "old_kid": old_es256_kid,
        "new_kid": es256_kid,
    });
    if let Err(e) = audit
        .insert_event(
            "org_issuer_key_emergency_rotation",
            user_id,
            email,
            &es256_event.to_string(),
        )
        .await
    {
        tracing::warn!(
            error = %e,
            "failed to write org_issuer_key_emergency_rotation (ES256) audit event"
        );
    }
    let rs256_event = serde_json::json!({
        "action": "emergency_rotate_org_issuer_key",
        "org_id": org_id,
        "alg": JwsAlgorithm::Rs256.as_str(),
        "old_kid": old_rs256_kid,
        "new_kid": rs256_kid,
    });
    if let Err(e) = audit
        .insert_event(
            "org_issuer_key_emergency_rotation",
            user_id,
            email,
            &rs256_event.to_string(),
        )
        .await
    {
        tracing::warn!(
            error = %e,
            "failed to write org_issuer_key_emergency_rotation (RS256) audit event"
        );
    }

    tracing::warn!(org_id, "emergency org issuer key rotation completed");
    Ok(())
}

#[cfg(test)]
#[expect(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::assertions_on_constants,
    reason = "test code: panic on assertion failure is acceptable"
)]
mod tests {
    use std::sync::Arc;

    use base64::Engine;
    use base64::engine::general_purpose::STANDARD;
    use jiff::{Span, Timestamp};

    use super::{
        ActivateOutcome, PUBLISH_AHEAD_HOURS, RETIREMENT_FLOOR_HOURS, RETIREMENT_MARGIN_HOURS,
        SigningKeyState, org_issuer_or_base, state_priority, try_activate_org_key_rotation,
    };
    use crate::db::{
        JwsAlgorithm, OrgSigningKeyDoc, Organization, claim_subdomain, deterministic_org_key_id,
        deterministic_org_key_next_id, deterministic_org_key_previous_id, get_org_signing_key,
        get_org_signing_key_previous, try_insert_org_signing_key_next,
    };
    use crate::services::oidc::{Jwk, OidcSigningKey, resolve_org_keys, stage_org_key_rotation};
    use crate::test_utils::{create_test_org, test_app_state_encrypted, test_config};

    fn org(subdomain: Option<&str>) -> Organization {
        Organization {
            id: "org1".to_string(),
            domain: "acme.com".to_string(),
            name: None,
            created_at: Timestamp::now(),
            created_by_user_id: None,
            additional_domains: Vec::new(),
            subdomain: subdomain.map(String::from),
        }
    }

    #[test]
    fn issuer_is_org_subdomain_or_base_url() {
        let config = test_config();
        // No org, or an org without a subdomain -> shared base URL.
        assert_eq!(org_issuer_or_base(&config, None).unwrap(), config.base_url);
        assert_eq!(
            org_issuer_or_base(&config, Some(&org(None))).unwrap(),
            config.base_url
        );
        // A claimed subdomain -> the org issuer host.
        assert_eq!(
            org_issuer_or_base(&config, Some(&org(Some("acme")))).unwrap(),
            "https://acme.test.example.com"
        );
    }

    #[test]
    fn state_priority_ordering_is_correct() {
        assert!(
            state_priority(&SigningKeyState::Active)
                < state_priority(&SigningKeyState::Pending {
                    activate_at: Timestamp::now()
                })
        );
        assert!(
            state_priority(&SigningKeyState::Pending {
                activate_at: Timestamp::now()
            }) < state_priority(&SigningKeyState::Retiring {
                not_after: Timestamp::now()
            })
        );
    }

    // -----------------------------------------------------------------------
    // SigningKeyState serde round-trip
    // -----------------------------------------------------------------------

    #[test]
    fn signing_key_state_serde_round_trip() {
        // Fixed timestamp so the JSON is deterministic.
        let ts = Timestamp::from_second(1_700_000_000).unwrap();
        let cases = [
            SigningKeyState::Active,
            SigningKeyState::Pending { activate_at: ts },
            SigningKeyState::Retiring { not_after: ts },
        ];
        for state in &cases {
            let json = serde_json::to_string(state).expect("serialise");
            let back: SigningKeyState = serde_json::from_str(&json).expect("deserialise");
            assert_eq!(state, &back, "round-trip failed for {json}");
        }
    }

    #[test]
    fn active_and_pending_have_no_not_after_retiring_does() {
        let ts = Timestamp::from_second(1_700_000_000).unwrap();

        // Active and Pending carry no `not_after` timestamp.
        let active = SigningKeyState::Active;
        let pending = SigningKeyState::Pending { activate_at: ts };
        assert!(
            matches!(active, SigningKeyState::Active),
            "Active must not be Retiring"
        );
        assert!(
            !matches!(active, SigningKeyState::Retiring { .. }),
            "Active carries no not_after"
        );
        assert!(
            !matches!(pending, SigningKeyState::Retiring { .. }),
            "Pending carries no not_after"
        );

        // Retiring carries not_after and it must match what was stored.
        let retiring = SigningKeyState::Retiring { not_after: ts };
        let not_after = match retiring {
            SigningKeyState::Retiring { not_after } => not_after,
            _ => panic!("must be Retiring"),
        };
        assert_eq!(
            not_after, ts,
            "Retiring.not_after must match the stored timestamp"
        );
    }

    // -----------------------------------------------------------------------
    // Schedule math: constants and M1 floor
    // -----------------------------------------------------------------------

    /// PUBLISH_AHEAD must be >= the OIDC discovery `max-age` (1 h = 3600 s so
    /// 1 h is the minimum meaningful value). If this fails, relying parties may
    /// cache a discovery document that doesn't yet include the `kid` before we
    /// start signing with it.
    ///
    /// The value is also pinned to its decided constant (S2 locked decision:
    /// 24 h was chosen to accommodate AWS JWKS caching of up to a few hours
    /// while erring large; changing it requires team consensus).
    #[test]
    fn publish_ahead_satisfies_oidc_discovery_max_age_constraint() {
        // S2 locked decision: 24h (err-large vs AWS JWKS caching up to ~1h).
        // Changing this value requires updating the test assertion AND re-validating
        // the AWS federation guidance in docs/src/reference/environment-variables.md.
        assert_eq!(
            PUBLISH_AHEAD_HOURS, 24,
            "PUBLISH_AHEAD_HOURS is a locked constant (S2); \
             update this test and the AWS federation docs if you change it"
        );

        // Functional lower bound: must be >= discovery max-age (1h) so relying
        // parties always see the new kid in JWKS before we start signing with it.
        const DISCOVERY_MAX_AGE_HOURS: i64 = 1;
        assert!(
            PUBLISH_AHEAD_HOURS >= DISCOVERY_MAX_AGE_HOURS,
            "PUBLISH_AHEAD_HOURS ({PUBLISH_AHEAD_HOURS}) must be >= discovery max-age ({DISCOVERY_MAX_AGE_HOURS}h)"
        );
    }

    /// M1 floor: `max(session_hours, RETIREMENT_FLOOR_HOURS)` ensures the
    /// retirement window covers tokens minted under the old key even when the
    /// operator reduced `session_hours` below 8 h before rotating.
    #[test]
    fn retirement_floor_covers_session_hours_below_minimum() {
        // session_hours=4 is below the floor (8h) → floor must kick in.
        let session_h_low: i64 = 4;
        let effective_low = session_h_low.max(RETIREMENT_FLOOR_HOURS);
        assert_eq!(
            effective_low, RETIREMENT_FLOOR_HOURS,
            "floor must apply when session_hours ({session_h_low}) < RETIREMENT_FLOOR_HOURS ({RETIREMENT_FLOOR_HOURS})"
        );

        // session_hours=12 is above the floor → the actual value applies.
        let session_h_high: i64 = 12;
        let effective_high = session_h_high.max(RETIREMENT_FLOOR_HOURS);
        assert_eq!(
            effective_high, session_h_high,
            "actual session_hours must apply when session_hours > RETIREMENT_FLOOR_HOURS"
        );

        // session_hours exactly equal to the floor → floor (tie).
        let session_h_eq: i64 = RETIREMENT_FLOOR_HOURS;
        let effective_eq = session_h_eq.max(RETIREMENT_FLOOR_HOURS);
        assert_eq!(effective_eq, RETIREMENT_FLOOR_HOURS);
    }

    /// Verify the N5 caveat: the M1 floor does NOT cover a reduction from above
    /// 8 h (e.g. 24 h → 8 h), only a reduction below 8 h. The mitigation for
    /// that case is the operator doc-note ("don't shrink session_hours immediately
    /// before rotating"). This test documents the limitation.
    #[test]
    fn retirement_floor_does_not_cover_reduction_from_above_floor() {
        // If session_hours was 24h but we reduced to 8h just before rotating,
        // the floor computes max(8, 8) = 8h — under-covering tokens minted when
        // session_hours was 24h. This is the documented N5 caveat.
        let reduced_hours: i64 = 8;
        let floor_result = reduced_hours.max(RETIREMENT_FLOOR_HOURS);
        // The floor gives 8h, but outstanding tokens may have up to 24h TTL.
        // The test asserts the known limitation (floor = 8 < 24).
        assert_eq!(
            floor_result, 8,
            "floor cannot distinguish between original 8h or reduced-from-24h"
        );
    }

    // -----------------------------------------------------------------------
    // Slot ID uniqueness (migration parity — current slot == pre-rotation ID)
    // -----------------------------------------------------------------------

    /// The current-slot function (`deterministic_org_key_id`) must be
    /// byte-identical to the pre-rotation deterministic ID used before this
    /// PR so existing rows deserialise without a migration. This test locks the
    /// hash prefix to `"org_signing_key\0"`.
    #[test]
    fn current_slot_id_uses_original_hash_prefix() {
        use aws_lc_rs::digest::{self, SHA256};

        let org_id = "migration-parity-test-org";
        let alg = JwsAlgorithm::Es256;

        // Recompute the hash the original way (before next/prev slots existed).
        let mut ctx = digest::Context::new(&SHA256);
        ctx.update(b"org_signing_key\0");
        ctx.update(org_id.as_bytes());
        ctx.update(b"\0");
        ctx.update(alg.as_str().as_bytes());
        let expected = hex::encode(ctx.finish().as_ref());

        let actual = deterministic_org_key_id(org_id, alg);
        assert_eq!(
            actual, expected,
            "current slot ID diverged from pre-rotation formula"
        );
    }

    #[test]
    fn three_slot_ids_are_mutually_distinct_per_org_and_alg() {
        for alg in [JwsAlgorithm::Es256, JwsAlgorithm::Rs256] {
            let current = deterministic_org_key_id("test-org", alg);
            let next = deterministic_org_key_next_id("test-org", alg);
            let prev = deterministic_org_key_previous_id("test-org", alg);

            assert_ne!(current, next, "{alg:?}: current == next slot (collision)");
            assert_ne!(
                current, prev,
                "{alg:?}: current == previous slot (collision)"
            );
            assert_ne!(next, prev, "{alg:?}: next == previous slot (collision)");

            // Verify determinism: same call twice → same result.
            assert_eq!(
                deterministic_org_key_id("test-org", alg),
                current,
                "{alg:?}: current slot ID is not deterministic"
            );
        }
        // Different orgs must produce different IDs for the same alg.
        let a = deterministic_org_key_id("org-a", JwsAlgorithm::Es256);
        let b = deterministic_org_key_id("org-b", JwsAlgorithm::Es256);
        assert_ne!(a, b, "different orgs must have distinct current slot IDs");
    }

    // -----------------------------------------------------------------------
    // `expires_at()` method (added to `SigningKeyState`)
    // -----------------------------------------------------------------------

    #[test]
    fn expires_at_is_some_only_for_retiring() {
        let ts = Timestamp::from_second(1_700_000_000).unwrap();
        assert!(
            SigningKeyState::Active.expires_at().is_none(),
            "Active must not have an expiry"
        );
        assert!(
            SigningKeyState::Pending { activate_at: ts }
                .expires_at()
                .is_none(),
            "Pending must not have an expiry"
        );
        assert_eq!(
            SigningKeyState::Retiring { not_after: ts }.expires_at(),
            Some(ts),
            "Retiring must return Some(not_after)"
        );
    }

    // -----------------------------------------------------------------------
    // Async DB tests — encrypted store required (call test_app_state_encrypted)
    // -----------------------------------------------------------------------

    /// Set up an encrypted AppState with a fresh org that has a claimed subdomain.
    async fn setup_encrypted_with_subdomain() -> (Arc<crate::AppState>, String) {
        let state = test_app_state_encrypted().await;
        let org = create_test_org(&state.store, "acme.com").await;
        claim_subdomain(&state.store, &org.id, "acme-com")
            .await
            .unwrap();
        (state, org.id)
    }

    /// Verify that the resolver uses the Active slot's key for signing, not a
    /// Pending key.  After a stage the snapshot signer's kid must still match
    /// the current (Active) document, not the staged (Pending) next-slot.
    #[tokio::test]
    async fn resolver_signs_with_active_key_only() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();

        // First resolve creates the Active keys.
        let snap_before = resolve_org_keys(&state, Some(&org)).await.unwrap().unwrap();

        // Read the Active ES256 document to get its kid.
        let active_doc = get_org_signing_key(&state.store, &org_id, JwsAlgorithm::Es256)
            .await
            .unwrap()
            .unwrap();
        let active_kid = active_doc.data.kid.clone();

        // Stage rotation — inserts a Pending key with a future activate_at and
        // invalidates the cache (so the next resolve sees the Pending in JWKS).
        stage_org_key_rotation(&state.store, &org_id, &state.org_keys_cache)
            .await
            .unwrap();

        // Resolve again — must sign with the still-Active key, not the Pending one.
        let snap_after = resolve_org_keys(&state, Some(&org)).await.unwrap().unwrap();
        let signer_kid = snap_after.signers.es256.key_id().to_string();
        assert_eq!(
            signer_kid, active_kid,
            "resolver must sign with Active key (kid={active_kid}), \
             not the Pending successor after stage"
        );

        // The JWKS grows from 2 to 4 (Active+Pending for each alg) but the
        // kid for the before-snapshot signer must still appear in the JWKS.
        let before_kid = snap_before.signers.es256.key_id().to_string();
        let ec_kids: Vec<&str> = snap_after
            .jwks
            .iter()
            .filter_map(|jwk| {
                if let Jwk::Ec(ec) = jwk {
                    Some(ec.kid.as_str())
                } else {
                    None
                }
            })
            .collect();
        assert!(
            ec_kids.contains(&before_kid.as_str()),
            "Active key kid {before_kid} must still appear in JWKS after stage"
        );
    }

    /// Verify M2: RS256 JWKs precede ES256 JWKs in the ordered snapshot, and
    /// all kids across the full JWKS are distinct.
    #[tokio::test]
    async fn jwks_rsa_first_and_all_kids_distinct() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();

        resolve_org_keys(&state, Some(&org)).await.unwrap();
        // Stage so both algs have 2 keys (Active + Pending = 4 total).
        // stage_org_key_rotation invalidates the cache — no manual call needed.
        stage_org_key_rotation(&state.store, &org_id, &state.org_keys_cache)
            .await
            .unwrap();

        let snap = resolve_org_keys(&state, Some(&org)).await.unwrap().unwrap();
        assert_eq!(
            snap.jwks.len(),
            4,
            "expected 4 JWKs after stage (2 RS256 + 2 ES256)"
        );

        // M2: all Rsa JWKs must precede all Ec JWKs.
        let mut saw_ec = false;
        for jwk in &snap.jwks {
            match jwk {
                Jwk::Rsa(_) => assert!(
                    !saw_ec,
                    "M2 violation: RSA JWK appears after an EC JWK in the JWKS"
                ),
                Jwk::Ec(_) => saw_ec = true,
            }
        }
        assert!(saw_ec, "at least one EC JWK must be present");

        // All kids must be distinct.
        let kids: Vec<&str> = snap
            .jwks
            .iter()
            .map(|jwk| match jwk {
                Jwk::Rsa(rsa) => rsa.kid.as_str(),
                Jwk::Ec(ec) => ec.kid.as_str(),
            })
            .collect();
        let unique: std::collections::HashSet<&str> = kids.iter().copied().collect();
        assert_eq!(
            kids.len(),
            unique.len(),
            "JWKS contains duplicate kids: {kids:?}"
        );
    }

    /// M1 floor: when session_hours < RETIREMENT_FLOOR_HOURS, the retirement
    /// window uses the floor so tokens minted under a short session cap are
    /// still covered by the old key being present in the JWKS.
    #[tokio::test]
    async fn schedule_math_m1_floor_applies_when_session_hours_is_below_8() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();
        resolve_org_keys(&state, Some(&org)).await.unwrap();

        // Insert a pending ES256 key with activate_at in the past so the
        // activation fires immediately.
        let activate_at = Timestamp::now()
            .checked_sub(Span::new().seconds(1))
            .unwrap();
        let der = OidcSigningKey::generate_pkcs8_der().unwrap();
        let kid = OidcSigningKey::from_pkcs8_der(&der)
            .unwrap()
            .key_id()
            .to_string();
        let pending_doc = OrgSigningKeyDoc {
            org_id: org_id.clone(),
            alg: JwsAlgorithm::Es256,
            kid,
            private_pkcs8_der_b64: STANDARD.encode(&*der).into(),
            state: SigningKeyState::Pending { activate_at },
        };
        try_insert_org_signing_key_next(&state.store, &pending_doc)
            .await
            .unwrap();

        // Activate with session_hours=1 (below the 8h floor).
        let outcome = try_activate_org_key_rotation(&state.store, &org_id, JwsAlgorithm::Es256, 1)
            .await
            .unwrap();
        assert!(
            matches!(outcome, ActivateOutcome::Activated { .. }),
            "expected Activated, got {outcome:?}"
        );

        // The retiring key's not_after must be >= activate_at + (floor + margin).
        let floor_window = RETIREMENT_FLOOR_HOURS.saturating_add(RETIREMENT_MARGIN_HOURS);
        let min_not_after = activate_at
            .checked_add(Span::new().hours(floor_window))
            .unwrap();

        let retiring = get_org_signing_key_previous(&state.store, &org_id, JwsAlgorithm::Es256)
            .await
            .unwrap()
            .expect("retiring key must occupy the previous slot after activation");
        let SigningKeyState::Retiring { not_after } = retiring.data.state else {
            panic!("previous slot must be in Retiring state after activation");
        };
        assert!(
            not_after >= min_not_after,
            "not_after ({not_after}) must be >= activate_at + {floor_window}h ({min_not_after})"
        );
    }

    /// `AlreadyDone`: when the previous slot already holds a Retiring key, a
    /// concurrent instance already completed activation — the call returns
    /// `Ok(AlreadyDone)` without touching the DB (CAS-first ordering, S3).
    /// GAP5: M1 floor also applies to RS256 (same `RETIREMENT_FLOOR_HOURS`
    /// constant and `try_activate_org_key_rotation` code path as ES256).
    #[tokio::test]
    async fn schedule_math_m1_floor_applies_to_rs256_as_well() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();
        resolve_org_keys(&state, Some(&org)).await.unwrap();

        let activate_at = Timestamp::now()
            .checked_sub(Span::new().seconds(1))
            .unwrap();
        let der = tokio::task::spawn_blocking(
            crate::services::oidc::OidcRsaSigningKey::generate_pkcs8_der,
        )
        .await
        .unwrap()
        .unwrap();
        let kid = crate::services::oidc::OidcRsaSigningKey::from_pkcs8_der(&der)
            .unwrap()
            .key_id()
            .to_string();
        let pending_doc = OrgSigningKeyDoc {
            org_id: org_id.clone(),
            alg: JwsAlgorithm::Rs256,
            kid,
            private_pkcs8_der_b64: STANDARD.encode(&*der).into(),
            state: SigningKeyState::Pending { activate_at },
        };
        try_insert_org_signing_key_next(&state.store, &pending_doc)
            .await
            .unwrap();

        let outcome = try_activate_org_key_rotation(&state.store, &org_id, JwsAlgorithm::Rs256, 1)
            .await
            .unwrap();
        assert!(
            matches!(outcome, ActivateOutcome::Activated { .. }),
            "expected Activated for RS256, got {outcome:?}"
        );

        let floor_window = RETIREMENT_FLOOR_HOURS.saturating_add(RETIREMENT_MARGIN_HOURS);
        let min_not_after = activate_at
            .checked_add(Span::new().hours(floor_window))
            .unwrap();

        let retiring = get_org_signing_key_previous(&state.store, &org_id, JwsAlgorithm::Rs256)
            .await
            .unwrap()
            .expect("retiring RS256 key must occupy the previous slot");
        let SigningKeyState::Retiring { not_after } = retiring.data.state else {
            panic!("previous RS256 slot must be in Retiring state");
        };
        assert!(
            not_after >= min_not_after,
            "RS256 not_after ({not_after}) must be >= activate_at + {floor_window}h"
        );
    }

    #[tokio::test]
    async fn activate_returns_already_done_when_previous_slot_is_occupied() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();
        resolve_org_keys(&state, Some(&org)).await.unwrap();

        // Insert a Pending key with activate_at in the past.
        let activate_at = Timestamp::now()
            .checked_sub(Span::new().seconds(1))
            .unwrap();
        let pending_der = OidcSigningKey::generate_pkcs8_der().unwrap();
        let pending_kid = OidcSigningKey::from_pkcs8_der(&pending_der)
            .unwrap()
            .key_id()
            .to_string();
        try_insert_org_signing_key_next(
            &state.store,
            &OrgSigningKeyDoc {
                org_id: org_id.clone(),
                alg: JwsAlgorithm::Es256,
                kid: pending_kid,
                private_pkcs8_der_b64: STANDARD.encode(&*pending_der).into(),
                state: SigningKeyState::Pending { activate_at },
            },
        )
        .await
        .unwrap();

        // Seed the previous slot as if a peer already finished activation.
        let retiring_der = OidcSigningKey::generate_pkcs8_der().unwrap();
        let retiring_kid = OidcSigningKey::from_pkcs8_der(&retiring_der)
            .unwrap()
            .key_id()
            .to_string();
        let not_after = Timestamp::now().checked_add(Span::new().hours(10)).unwrap();
        let prev_id = deterministic_org_key_previous_id(&org_id, JwsAlgorithm::Es256);
        state
            .store
            .insert_with_id(
                &prev_id,
                &OrgSigningKeyDoc {
                    org_id: org_id.clone(),
                    alg: JwsAlgorithm::Es256,
                    kid: retiring_kid,
                    private_pkcs8_der_b64: STANDARD.encode(&*retiring_der).into(),
                    state: SigningKeyState::Retiring { not_after },
                },
            )
            .await
            .unwrap();

        // Activation must see the occupied previous slot and short-circuit.
        let outcome = try_activate_org_key_rotation(&state.store, &org_id, JwsAlgorithm::Es256, 8)
            .await
            .unwrap();
        assert_eq!(
            outcome,
            ActivateOutcome::AlreadyDone,
            "expected AlreadyDone when previous slot is occupied by a Retiring key"
        );
    }

    #[tokio::test]
    async fn activate_returns_nothing_staged_when_no_pending_exists() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();
        resolve_org_keys(&state, Some(&org)).await.unwrap();

        let outcome = try_activate_org_key_rotation(&state.store, &org_id, JwsAlgorithm::Es256, 8)
            .await
            .unwrap();
        assert_eq!(
            outcome,
            ActivateOutcome::NothingStaged,
            "expected NothingStaged when no pending key exists"
        );
    }

    #[tokio::test]
    async fn activate_returns_not_due_when_activate_at_is_in_future() {
        let (state, org_id) = setup_encrypted_with_subdomain().await;
        let org = crate::db::get_organization(&state.store, &org_id)
            .await
            .unwrap()
            .unwrap();
        resolve_org_keys(&state, Some(&org)).await.unwrap();

        // stage_org_key_rotation sets activate_at = now + PUBLISH_AHEAD_HOURS.
        stage_org_key_rotation(&state.store, &org_id, &state.org_keys_cache)
            .await
            .unwrap();

        let outcome = try_activate_org_key_rotation(&state.store, &org_id, JwsAlgorithm::Es256, 8)
            .await
            .unwrap();
        assert_eq!(
            outcome,
            ActivateOutcome::NotDue,
            "expected NotDue because activate_at is {PUBLISH_AHEAD_HOURS}h ahead"
        );
    }

    /// GAP4: `emergency_rotate_org_keys` must return `Err` when the org has no
    /// Active current-slot key (e.g. called on an org whose subdomain was
    /// claimed but keys were never bootstrapped, or after a bug cleared them).
    #[tokio::test]
    async fn emergency_returns_err_when_no_current_key_exists() {
        use crate::services::oidc::emergency_rotate_org_keys;

        let (state, org_id) = setup_encrypted_with_subdomain().await;
        // Deliberately do NOT call resolve_org_keys — no Active key is created.

        let result = emergency_rotate_org_keys(
            &state.store,
            &org_id,
            &state.audit,
            &state.org_keys_cache,
            None,
            None,
        )
        .await;
        assert!(
            result.is_err(),
            "emergency rotation must fail when no current key exists"
        );
        let msg = result.unwrap_err().to_string();
        assert!(
            msg.contains("no current ES256 key"),
            "error must mention the missing ES256 key; got: {msg}"
        );
    }
}
