[package]
name = "vouch-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Integration tests for Vouch"
publish = false

# Allow panics in tests
[lints.clippy]
expect_used = "allow"
unwrap_used = "allow"
panic = "allow"
indexing_slicing = "allow"

[lints.rust]
unsafe_code = "deny"

[dependencies]
anyhow = { workspace = true, features = ["std"] }
aws-lc-rs = { workspace = true }
base64 = { workspace = true, features = ["std"] }
ciborium = { workspace = true }
hex = { workspace = true, features = ["std"] }
jiff = { workspace = true, features = ["std", "serde", "tz-system"] }
secrecy = { workspace = true, features = ["serde"] }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "net", "io-util", "sync", "signal", "time"] }
uuid = { workspace = true, features = ["v7", "serde", "std"] }
vouch-agent = { path = "../vouch-agent", features = ["test-utils"] }
vouch-cli = { path = "../vouch-cli", features = ["test-utils"] }
vouch-common = { path = "../vouch-common" }
vouch-server = { path = "../vouch-server", features = ["test-utils"] }

[dev-dependencies]
proptest = { workspace = true, features = ["std"] }
tempfile = { workspace = true }
