#!/usr/bin/env python3
"""Render the normative coverage report.

Reads three committed files and writes ``specs/coverage-report.md``:

* ``specs/requirements.tsv`` -- every normative statement in the cached
  corpus, produced by ``audit-normative.py``.
* ``specs/audit-scope.tsv`` -- which specifications impose obligations on
  Vouch.
* ``specs/coverage-baseline.tsv`` -- the statements with no citing test.

This script does **not** scan the test suite. The scan lives in
``crates/vouch-tests/tests/spec_coverage.rs``, which owns both the gate and
the baseline it checks; a second implementation here drifted from it by 627
statements before this was split apart. Regenerate the baseline first:

    scripts/audit-normative.py
    UPDATE_SPEC_COVERAGE_BASELINE=1 cargo test -p vouch-tests --test spec_coverage
    scripts/audit-coverage.py

Usage:
    scripts/audit-coverage.py            # write specs/coverage-report.md
    scripts/audit-coverage.py --json     # machine-readable summary
    scripts/audit-coverage.py --spec rfc9449   # gaps for one specification
"""

from __future__ import annotations

import argparse
import collections
import csv
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
REQUIREMENTS = REPO / "specs" / "requirements.tsv"
SCOPE = REPO / "specs" / "audit-scope.tsv"
EXCLUSIONS = REPO / "specs" / "audit-exclusions.tsv"
BASELINE = REPO / "specs" / "coverage-baseline.tsv"
REPORT = REPO / "specs" / "coverage-report.md"


def load_rows(path: Path) -> list[dict]:
    with path.open(encoding="utf-8") as fh:
        lines = [l for l in fh if not l.startswith("#") and l.strip()]
    return list(csv.DictReader(lines, delimiter="\t"))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--json", action="store_true")
    ap.add_argument("--spec", help="list the uncited statements for one specification")
    args = ap.parse_args()

    if not BASELINE.exists():
        print(
            "specs/coverage-baseline.tsv is missing; generate it with\n"
            "  UPDATE_SPEC_COVERAGE_BASELINE=1 cargo test -p vouch-tests --test spec_coverage",
            file=sys.stderr,
        )
        return 1

    scope = {r["spec_id"]: r for r in load_rows(SCOPE)}
    exclusions = load_rows(EXCLUSIONS)

    def excluded(req: dict) -> bool:
        """True when a section-level exclusion covers this statement.

        A prefix covers a section and everything beneath it: "4" covers 4, 4.8
        and 4.8.1, but not 40.
        """
        for e in exclusions:
            if e["spec_id"] != req["spec"]:
                continue
            prefix, section = e["section_prefix"], req["section"]
            if section == prefix or section.startswith(prefix + "."):
                return True
        return False

    in_scope = [
        r for r in load_rows(REQUIREMENTS) if scope.get(r["spec"], {}).get("scope") != "reference"
    ]
    reqs = [r for r in in_scope if not excluded(r)]
    n_excluded = len(in_scope) - len(reqs)
    uncited = {r["req_id"] for r in load_rows(BASELINE)}

    stale = uncited - {r["req_id"] for r in reqs}
    if stale:
        print(
            f"warning: {len(stale)} baseline entries are not in requirements.tsv; "
            "regenerate the baseline",
            file=sys.stderr,
        )

    if args.spec:
        for r in reqs:
            if r["spec"] == args.spec and r["req_id"] in uncited:
                print(f"[{r['strength']}] §{r['section']}  {r['text'][:150]}")
        return 0

    by_spec: dict[str, dict] = collections.defaultdict(
        lambda: {"total": 0, "cited": 0, "must": 0, "must_gap": 0}
    )
    for r in reqs:
        s = by_spec[r["spec"]]
        s["total"] += 1
        is_cited = r["req_id"] not in uncited
        s["cited"] += 1 if is_cited else 0
        if r["strength"] in ("MUST", "MUST NOT"):
            s["must"] += 1
            if not is_cited:
                s["must_gap"] += 1

    total = len(reqs)
    cited = sum(s["cited"] for s in by_spec.values())

    if args.json:
        print(json.dumps({"total": total, "cited": cited, "by_spec": by_spec}, indent=2))
        return 0

    lines = [
        "# Normative coverage report",
        "",
        "Generated by `scripts/audit-coverage.py` from `specs/coverage-baseline.tsv`.",
        "Do not edit by hand.",
        "",
        f"In-scope normative statements: **{total}**  ",
        f"With at least one citing test: **{cited}** ({cited * 100 // max(total, 1)}%)  ",
        f"With no citing test: **{total - cited}**",
        "",
        f"A further **{n_excluded}** statements of in-scope specifications are excluded",
        "by `specs/audit-exclusions.tsv` as addressed to an actor Vouch is not, or",
        "covering a feature Vouch does not implement by design. They are not counted",
        "above: they are not owed, so they are not a gap. Each carries its reason in",
        "that file.",
        "",
        "A statement counts as cited when some test function names its specification",
        "and section. Linkage is section-level and deliberately optimistic: it",
        "establishes that a statement is untested, not that a cited one is tested",
        "well. The scan and the gate live in",
        "`crates/vouch-tests/tests/spec_coverage.rs`.",
        "",
        "| Spec | Scope | Statements | Cited | MUST/MUST NOT | MUST gaps |",
        "|---|---|---:|---:|---:|---:|",
    ]
    for spec, s in sorted(by_spec.items(), key=lambda kv: (-kv[1]["must_gap"], kv[0])):
        lines.append(
            f"| `{spec}` | {scope[spec]['scope']} | {s['total']} | {s['cited']} "
            f"| {s['must']} | {s['must_gap']} |"
        )
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"in-scope: {total}   cited: {cited}   uncited: {total - cited}   excluded: {n_excluded}")
    print(f"wrote {REPORT.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
