#!/bin/bash
echo ""
echo "Vouch installed successfully!"
echo ""
echo "To start the agent automatically on login:"
echo "  systemctl --user enable --now vouch-agent"
echo ""
echo "For servers/headless systems (persists after logout):"
echo "  sudo loginctl enable-linger \$USER"
echo "  systemctl --user enable --now vouch-agent"
echo ""
echo "Note: Run these commands as a regular user, not root."
echo ""
